SkylineMatrixBase< Derived > Class Template Reference
SkylineMatrixBase< Derived > Class Template Reference
Skyline module
Base class of any skyline matrices or skyline expressions.
#include <SkylineMatrixBase.h>
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime,
MaxRowsAtCompileTime,
MaxColsAtCompileTime,
MaxSizeAtCompileTime,
IsVectorAtCompileTime,
Flags,
CoeffReadCost,
IsRowMajor
}
typedef internal::index
< StorageKind >::type Index
typedef internal::traits
< Derived >::Scalar Scalar
typedef internal::traits
< Derived >::StorageKind StorageKind
Public Member Functions
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Index cols () const
const internal::eval< Derived,
IsSkyline >::type eval () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &dst) const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
Index nonZeros () const
template<typename OtherDerived >
const SkylineProductReturnType
< Derived, OtherDerived >
::Type operator* (const MatrixBase< OtherDerived > &other) const
Derived & operator= (const Derived &other)
template<typename OtherDerived >
Derived & operator= (const SkylineMatrixBase< OtherDerived > &other)
template<typename Lhs , typename Rhs >
Derived & operator= (const SkylineProduct< Lhs, Rhs, SkylineTimeSkylineProduct > &product)
Index outerSize () const
Index rows () const
Index size () const
Matrix< Scalar,
RowsAtCompileTime,
ColsAtCompileTime > toDense () const
Protected Attributes
bool m_isRValue
Friends
std::ostream & operator<< (std::ostream &s, const SkylineMatrixBase &m)
Detailed Description
template<typename Derived>
class Eigen::SkylineMatrixBase< Derived >
Base class of any skyline matrices or skyline expressions.
Parameters
Derived
Member Enumeration Documentation
anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See Also
RowsAtCompileTime, ColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Member Function Documentation
Index cols () const inline
Returns
the number of columns.
See Also
rows(), ColsAtCompileTime
Referenced by SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::innerSize(), SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::outerSize(), and SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::size().
const internal::eval<Derived, IsSkyline>::type eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Index innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
Index nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
Index outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
Index rows () const inline
Returns
the number of rows.
See Also
cols(), RowsAtCompileTime
Referenced by SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::innerSize(), SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::outerSize(), and SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::size().
Index size () const inline
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols(), SizeAtCompileTime.
The documentation for this class was generated from the following files:
SkylineMatrixBase.h
SkylineProduct.h