BlockMethods.h File Reference
BlockMethods.h File Reference
Functions
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol)
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
RowsBlockXpr bottomRows (Index n)
template<int N>
NRowsBlockXpr< N >::Type bottomRows ()
ColXpr col (Index i)
ColsBlockXpr leftCols (Index n)
template<int N>
NColsBlockXpr< N >::Type leftCols ()
ColsBlockXpr middleCols (Index startCol, Index numCols)
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol)
RowsBlockXpr middleRows (Index startRow, Index numRows)
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow)
ColsBlockXpr rightCols (Index n)
template<int N>
NColsBlockXpr< N >::Type rightCols ()
RowXpr row (Index i)
Block< Derived > topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
Block< Derived > topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
RowsBlockXpr topRows (Index n)
template<int N>
NRowsBlockXpr< N >::Type topRows ()
Function Documentation
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) [inline]
Returns:
a dynamic-size expression of a block in *this.
Parameters:
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block(1, 1, 2, 2):" << endl << m.block(1, 1, 2, 2) << endl;
m.block(1, 1, 2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block(1, 1, 2, 2):
-6 1
-3 0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note:
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also:
class Block, block(Index,Index)
This is the const version of block(Index,Index,Index,Index).
Referenced by CommaInitializer< XprType >::operator,().
const Block< const Derived, BlockRows, BlockCols > block (Index startRow, Index startCol) [inline]
Returns:
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters:
startRow the first row in the block
startCol the first column in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block<2,2>(1,1):" << endl << m.block<2,2>(1,1) << endl;
m.block<2,2>(1,1).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block<2,2>(1,1):
-6 1
-3 0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note:
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
 m.template block<3,3>(1,1);
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of block<>(Index, Index).
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) [inline]
Returns:
a dynamic-size expression of a bottom-left corner of *this.
Parameters:
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner(2, 2):" << endl;
cout << m.bottomLeftCorner(2, 2) << endl;
m.bottomLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner(2, 2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomLeftCorner(Index, Index).
const Block< const Derived, CRows, CCols > bottomLeftCorner () [inline]
Returns:
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,2>():" << endl;
cout << m.bottomLeftCorner<2,2>() << endl;
m.bottomLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,2>():
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomLeftCorner<int, int>().
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) [inline]
Returns:
a dynamic-size expression of a bottom-right corner of *this.
Parameters:
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner(2, 2):" << endl;
cout << m.bottomRightCorner(2, 2) << endl;
m.bottomRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner(2, 2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRightCorner(Index, Index).
const Block< const Derived, CRows, CCols > bottomRightCorner () [inline]
Returns:
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,2>():" << endl;
cout << m.bottomRightCorner<2,2>() << endl;
m.bottomRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,2>():
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRightCorner<int, int>().
ConstRowsBlockXpr bottomRows (Index n) [inline]
Returns:
a block consisting of the bottom rows of *this.
Parameters:
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows(2):" << endl;
cout << a.bottomRows(2) << endl;
a.bottomRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows(2):
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRows(Index).
ConstNRowsBlockXpr< N >::Type bottomRows () [inline]
Returns:
a block consisting of the bottom rows of *this.
Template Parameters:
N the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows<2>():" << endl;
cout << a.bottomRows<2>() << endl;
a.bottomRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows<2>():
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of bottomRows<int>().
ConstColXpr col (Index i) [inline]
Returns:
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.col(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 4 0
0 5 0
0 6 1
See also:
row(), class Block
This is the const version of col().
Referenced by MatrixBase< Derived >::applyHouseholderOnTheRight(), MatrixBase< Derived >::applyOnTheRight(), Reverse< MatrixType, Direction >::coeff(), ProductBase< SelfadjointProductMatrix< Lhs, LhsMode, false, Rhs, RhsMode, false >, Lhs, Rhs >::coeff(), CoeffBasedProduct< LhsNested, RhsNested, NestingFlags >::coeff(), Reverse< MatrixType, Direction >::coeffRef(), SwapWrapper< ExpressionType >::copyPacket(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), IncompleteLUT< _Scalar >::keep_diag::operator()(), SimplicialCholeskyBase< Derived >::keep_diag::operator()(), ForceAlignedAccess< ExpressionType >::packet(), NestByValue< ExpressionType >::packet(), Reverse< MatrixType, Direction >::packet(), TransposeImpl< MatrixType, Dense >::packet(), DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), ForceAlignedAccess< ExpressionType >::writePacket(), NestByValue< ExpressionType >::writePacket(), Reverse< MatrixType, Direction >::writePacket(), TransposeImpl< MatrixType, Dense >::writePacket(), and DenseCoeffsBase< Derived, WriteAccessors >::writePacket().
ConstColsBlockXpr leftCols (Index n) [inline]
Returns:
a block consisting of the left columns of *this.
Parameters:
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols(2):" << endl;
cout << a.leftCols(2) << endl;
a.leftCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols(2):
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of leftCols(Index).
ConstNColsBlockXpr< N >::Type leftCols () [inline]
Returns:
a block consisting of the left columns of *this.
Template Parameters:
N the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols<2>():" << endl;
cout << a.leftCols<2>() << endl;
a.leftCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols<2>():
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of leftCols<int>().
ConstColsBlockXpr middleCols (Index startCol, Index numCols) [inline]
Returns:
a block consisting of a range of columns of *this.
Parameters:
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleCols(1,3) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of middleCols(Index,Index).
ConstNColsBlockXpr< N >::Type middleCols (Index startCol) [inline]
Returns:
a block consisting of a range of columns of *this.
Template Parameters:
N the number of columns in the block
Parameters:
startCol the index of the first column in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(:,1..3) =\n" << A.middleCols<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(:,1..3) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of middleCols<int>().
ConstRowsBlockXpr middleRows (Index startRow, Index numRows) [inline]
Returns:
a block consisting of a range of rows of *this.
Parameters:
startRow the index of the first row in the block
numRows the number of rows in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(2..3,:) =\n" << A.middleRows(2,2) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(2..3,:) =
 6  6 -3  5 -8
 6 -5  0 -8  6
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of middleRows(Index,Index).
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow) [inline]
Returns:
a block consisting of a range of rows of *this.
Template Parameters:
N the number of rows in the block
Parameters:
startRow the index of the first row in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleRows<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-2 -3  3  3 -5
 6  6 -3  5 -8
 6 -5  0 -8  6
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of middleRows<int>().
ConstColsBlockXpr rightCols (Index n) [inline]
Returns:
a block consisting of the right columns of *this.
Parameters:
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols(2):" << endl;
cout << a.rightCols(2) << endl;
a.rightCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols(2):
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of rightCols(Index).
ConstNColsBlockXpr< N >::Type rightCols () [inline]
Returns:
a block consisting of the right columns of *this.
Template Parameters:
N the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols<2>():" << endl;
cout << a.rightCols<2>() << endl;
a.rightCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols<2>():
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of rightCols<int>().
ConstRowXpr row (Index i) [inline]
Returns:
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.row(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 0 0
4 5 6
0 0 1
See also:
col(), class Block
This is the const version of row().
Referenced by MatrixBase< Derived >::applyHouseholderOnTheLeft(), MatrixBase< Derived >::applyOnTheLeft(), Reverse< MatrixType, Direction >::coeff(), CoeffBasedProduct< LhsNested, RhsNested, NestingFlags >::coeff(), Reverse< MatrixType, Direction >::coeffRef(), SwapWrapper< ExpressionType >::copyPacket(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), ForceAlignedAccess< ExpressionType >::packet(), NestByValue< ExpressionType >::packet(), Reverse< MatrixType, Direction >::packet(), TransposeImpl< MatrixType, Dense >::packet(), DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), IncompleteLUT< _Scalar >::QuickSplit(), ForceAlignedAccess< ExpressionType >::writePacket(), NestByValue< ExpressionType >::writePacket(), Reverse< MatrixType, Direction >::writePacket(), TransposeImpl< MatrixType, Dense >::writePacket(), and DenseCoeffsBase< Derived, WriteAccessors >::writePacket().
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) [inline]
Returns:
a dynamic-size expression of a top-left corner of *this.
Parameters:
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner(2, 2):" << endl;
cout << m.topLeftCorner(2, 2) << endl;
m.topLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner(2, 2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topLeftCorner(Index, Index).
const Block< const Derived, CRows, CCols > topLeftCorner () [inline]
Returns:
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,2>():" << endl;
cout << m.topLeftCorner<2,2>() << endl;
m.topLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,2>():
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topLeftCorner<int, int>().
const Block< const Derived > topRightCorner (Index cRows, Index cCols) [inline]
Returns:
a dynamic-size expression of a top-right corner of *this.
Parameters:
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner(2, 2):" << endl;
cout << m.topRightCorner(2, 2) << endl;
m.topRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner(2, 2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topRightCorner(Index, Index).
const Block< const Derived, CRows, CCols > topRightCorner () [inline]
Returns:
an expression of a fixed-size top-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,2>():" << endl;
cout << m.topRightCorner<2,2>() << endl;
m.topRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,2>():
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topRightCorner<int, int>().
ConstRowsBlockXpr topRows (Index n) [inline]
Returns:
a block consisting of the top rows of *this.
Parameters:
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows(2):" << endl;
cout << a.topRows(2) << endl;
a.topRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows(2):
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topRows(Index).
ConstNRowsBlockXpr< N >::Type topRows () [inline]
Returns:
a block consisting of the top rows of *this.
Template Parameters:
N the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows<2>():" << endl;
cout << a.topRows<2>() << endl;
a.topRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows<2>():
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See also:
class Block, block(Index,Index,Index,Index)
This is the const version of topRows<int>().