SwapWrapper< ExpressionType > Class Template Reference
SwapWrapper< ExpressionType > Class Template Reference
Core module
#include <Swap.h>
Inherits type< SwapWrapper< ExpressionType > >.
Public Types
typedef
internal::dense_xpr_base
< SwapWrapper >::type Base
typedef
internal::packet_traits
< Scalar >::type Packet
typedef internal::conditional
< internal::is_lvalue
< ExpressionType >::value,
Scalar, const Scalar >::type ScalarWithConstIfNotLvalue
Public Member Functions
Scalar & coeffRef (Index row, Index col)
Scalar & coeffRef (Index index)
Scalar & coeffRef (Index row, Index col) const
Scalar & coeffRef (Index index) const
Index cols () const
template<typename OtherDerived >
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
void copyCoeff (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index index, const DenseBase< OtherDerived > &other)
ScalarWithConstIfNotLvalue * data ()
const Scalar * data () const
ExpressionType & expression () const
Index innerStride () const
Index outerStride () const
Index rows () const
SwapWrapper (ExpressionType &xpr)
Protected Attributes
ExpressionType & m_expression
template<typename ExpressionType>
class Eigen::SwapWrapper< ExpressionType >
Member Typedef Documentation
typedef internal::dense_xpr_base<SwapWrapper>::type Base
typedef internal::packet_traits<Scalar>::type Packet
typedef internal::conditional< internal::is_lvalue<ExpressionType>::value, Scalar, const Scalar >::type ScalarWithConstIfNotLvalue
Constructor & Destructor Documentation
SwapWrapper (ExpressionType & xpr) [inline]
Member Function Documentation
Scalar& coeffRef (Index row, Index col) [inline]
References SwapWrapper< ExpressionType >::m_expression.
Scalar& coeffRef (Index index) [inline]
References SwapWrapper< ExpressionType >::m_expression.
Scalar& coeffRef (Index row, Index col) const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Scalar& coeffRef (Index index) const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Index cols (void) const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Referenced by SwapWrapper< ExpressionType >::copyCoeff(), and SwapWrapper< ExpressionType >::copyPacket().
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > & other) [inline]
References SwapWrapper< ExpressionType >::cols(), eigen_internal_assert, SwapWrapper< ExpressionType >::m_expression, and SwapWrapper< ExpressionType >::rows().
void copyCoeff (Index index, const DenseBase< OtherDerived > & other) [inline]
References eigen_internal_assert, and SwapWrapper< ExpressionType >::m_expression.
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > & other) [inline]
References col(), SwapWrapper< ExpressionType >::cols(), eigen_internal_assert, SwapWrapper< ExpressionType >::m_expression, row(), and SwapWrapper< ExpressionType >::rows().
void copyPacket (Index index, const DenseBase< OtherDerived > & other) [inline]
References eigen_internal_assert, and SwapWrapper< ExpressionType >::m_expression.
ScalarWithConstIfNotLvalue* data () [inline]
References SwapWrapper< ExpressionType >::m_expression.
const Scalar* data () const [inline]
References SwapWrapper< ExpressionType >::m_expression.
ExpressionType& expression () const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Index innerStride () const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Index outerStride () const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Index rows (void) const [inline]
References SwapWrapper< ExpressionType >::m_expression.
Referenced by SwapWrapper< ExpressionType >::copyCoeff(), and SwapWrapper< ExpressionType >::copyPacket().
Member Data Documentation
ExpressionType& m_expression [protected]
Referenced by SwapWrapper< ExpressionType >::coeffRef(), SwapWrapper< ExpressionType >::cols(), SwapWrapper< ExpressionType >::copyCoeff(), SwapWrapper< ExpressionType >::copyPacket(), SwapWrapper< ExpressionType >::data(), SwapWrapper< ExpressionType >::expression(), SwapWrapper< ExpressionType >::innerStride(), SwapWrapper< ExpressionType >::outerStride(), and SwapWrapper< ExpressionType >::rows().
The documentation for this class was generated from the following file:
Swap.h