SparseSymmetricPermutationProduct< MatrixType, UpLo > Class Template Reference
SparseSymmetricPermutationProduct< MatrixType, UpLo > Class Template Reference
#include <SparseSelfAdjointView.h>
Public Types
typedef internal::remove_all
< MatrixTypeNested >::type _MatrixTypeNested
typedef MatrixType::Index Index
typedef MatrixType::Nested MatrixTypeNested
typedef MatrixType::Scalar Scalar
typedef internal::traits
< SparseSymmetricPermutationProduct
< MatrixType, UpLo >
>::StorageKind StorageKind
typedef Matrix< Index, Dynamic, 1 > VectorI
Public Member Functions
void addTo (Dest &dst) const
void applyThisOnTheLeft (Dest &dst) const
void applyThisOnTheRight (Dest &dst) const
Index cols () const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & const_cast_derived () const
const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & const_derived () const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & derived ()
const
SparseSymmetricPermutationProduct
< MatrixType, UpLo > & derived () const
void evalTo (Dest &dst) const
template<typename DestScalar , int Options, typename DstIndex >
void evalTo (SparseMatrix< DestScalar, Options, DstIndex > &_dest) const
template<typename DestType , unsigned int DestUpLo>
void evalTo (SparseSelfAdjointView< DestType, DestUpLo > &dest) const
Index rows () const
Index size () const
SparseSymmetricPermutationProduct (const MatrixType &mat, const Perm &perm)
void subTo (Dest &dst) const
Protected Types
typedef PermutationMatrix
< Dynamic, Dynamic, Index > Perm
Protected Attributes
MatrixTypeNested m_matrix
const Perm & m_perm
template<typename MatrixType, int UpLo>
class Eigen::SparseSymmetricPermutationProduct< MatrixType, UpLo >
Member Typedef Documentation
typedef internal::remove_all<MatrixTypeNested>::type _MatrixTypeNested
typedef MatrixType::Index Index
Reimplemented from EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >.
typedef MatrixType::Nested MatrixTypeNested
typedef PermutationMatrix<Dynamic,Dynamic,Index> Perm [protected]
typedef MatrixType::Scalar Scalar
typedef internal::traits<SparseSymmetricPermutationProduct< MatrixType, UpLo > >::StorageKind StorageKind [inherited]
typedef Matrix<Index,Dynamic,1> VectorI
Constructor & Destructor Documentation
SparseSymmetricPermutationProduct (const MatrixType & mat, const Perm & perm) [inline]
Member Function Documentation
void addTo (Dest & dst) const [inline, inherited]
void applyThisOnTheLeft (Dest & dst) const [inline, inherited]
void applyThisOnTheRight (Dest & dst) const [inline, inherited]
Index cols (void) const [inline]
Returns:
the number of columns.
See also:
rows(), ColsAtCompileTime
Reimplemented from EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >.
References SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix.
SparseSymmetricPermutationProduct< MatrixType, UpLo > & const_cast_derived () const [inline, inherited]
const SparseSymmetricPermutationProduct< MatrixType, UpLo > & const_derived () const [inline, inherited]
SparseSymmetricPermutationProduct< MatrixType, UpLo > & derived () [inline, inherited]
Returns:
a reference to the derived object
const SparseSymmetricPermutationProduct< MatrixType, UpLo > & derived () const [inline, inherited]
Returns:
a const reference to the derived object
void evalTo (Dest & dst) const [inline, inherited]
void evalTo (SparseMatrix< DestScalar, Options, DstIndex > & _dest) const [inline]
References PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix, and SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_perm.
Referenced by SparseSelfAdjointView< MatrixType, UpLo >::operator=().
void evalTo (SparseSelfAdjointView< DestType, DestUpLo > & dest) const [inline]
References PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix, SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_perm, and SparseSelfAdjointView< MatrixType, UpLo >::matrix().
Index rows (void) const [inline]
Returns:
the number of rows.
See also:
cols(), RowsAtCompileTime
Reimplemented from EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >.
References SparseSymmetricPermutationProduct< MatrixType, UpLo >::m_matrix.
Index size () const [inline, inherited]
Returns:
the number of coefficients, which is rows()*cols().
See also:
rows(), cols(), SizeAtCompileTime.
void subTo (Dest & dst) const [inline, inherited]
Member Data Documentation
MatrixTypeNested m_matrix [protected]
Referenced by SparseSymmetricPermutationProduct< MatrixType, UpLo >::cols(), SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo(), and SparseSymmetricPermutationProduct< MatrixType, UpLo >::rows().
const Perm& m_perm [protected]
Referenced by SparseSymmetricPermutationProduct< MatrixType, UpLo >::evalTo().
The documentation for this class was generated from the following file:
SparseSelfAdjointView.h