DenseCoeffsBase< Derived, DirectAccessors > Class Template Reference
DenseCoeffsBase< Derived, DirectAccessors > Class Template Reference
Core module
Base class providing direct read-only coefficient access to matrices and arrays.
#include <DenseCoeffsBase.h>
Public Member Functions
CoeffReturnType coeff (Index row, Index col) const
CoeffReturnType coeff (Index index) const
Index cols () const
Index colStride () const
Derived & derived ()
const Derived & derived () const
Index innerStride () const
CoeffReturnType operator() (Index row, Index col) const
CoeffReturnType operator() (Index index) const
CoeffReturnType operator[] (Index index) const
Index outerStride () const
Index rows () const
Index rowStride () const
Index size () const
CoeffReturnType w () const
CoeffReturnType x () const
CoeffReturnType y () const
CoeffReturnType z () const
Detailed Description
template<typename Derived>
class Eigen::DenseCoeffsBase< Derived, DirectAccessors >
Base class providing direct read-only coefficient access to matrices and arrays.
Template Parameters
Derived Type of the derived class
DirectAccessors Constant indicating direct access
This class defines functions to work with strides which can be used to access entries directly. This class inherits DenseCoeffsBase<Derived, ReadOnlyAccessors> which defines functions to access entries read-only using operator() .
See Also
The class hierarchy
Member Function Documentation
CoeffReturnType coeff (Index row, Index col) const inline inherited
Short version: don't use this function, use operator()(Index,Index) const instead.
Long version: this function is similar to operator()(Index,Index) const , but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator()(Index,Index) const .
See Also
operator()(Index,Index) const, coeffRef(Index,Index), coeff(Index) const
CoeffReturnType coeff (Index index) const inline inherited
Short version: don't use this function, use operator[](Index) const instead.
Long version: this function is similar to operator[](Index) const , but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameter index is in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator[](Index) const .
See Also
operator[](Index) const, coeffRef(Index), coeff(Index,Index) const
Index cols (void) const inline inherited
Returns
the number of columns.
See Also
rows(), ColsAtCompileTime
Referenced by Array< Index, 64, 1, DontAlign >::Array(), Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
Index colStride () const inline
Returns
the pointer increment between two consecutive columns.
See Also
innerStride(), outerStride(), rowStride()
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::imag(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), RotationBase< Derived, 3 >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), SparseMatrixBase< Derived >::operator*(), Transform< Scalar, Dim, Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), DenseBase< Derived >::operator=(), Transform< Scalar, Dim, Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), Transform< Scalar, Dim, Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
Index innerStride () const inline
Returns
the pointer increment between two consecutive elements within a slice in the inner direction.
See Also
outerStride(), rowStride(), colStride()
CoeffReturnType operator() (Index row, Index col) const inline inherited
Returns
the coefficient at given the given row and column.
See Also
operator()(Index,Index), operator[](Index)
CoeffReturnType operator() (Index index) const inline inherited
Returns
the coefficient at given index.
This is synonymous to operator[](Index) const.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See Also
operator[](Index), operator()(Index,Index) const, x() const, y() const, z() const, w() const
CoeffReturnType operator[] (Index index) const inline inherited
Returns
the coefficient at given index.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See Also
operator[](Index), operator()(Index,Index) const, x() const, y() const, z() const, w() const
Index outerStride () const inline
Returns
the pointer increment between two consecutive inner slices (for example, between two consecutive columns in a column-major matrix).
See Also
innerStride(), rowStride(), colStride()
Index rows (void) const inline inherited
Returns
the number of rows.
See Also
cols(), RowsAtCompileTime
Referenced by Array< Index, 64, 1, DontAlign >::Array(), Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
Index rowStride () const inline
Returns
the pointer increment between two consecutive rows.
See Also
innerStride(), outerStride(), colStride()
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols(), SizeAtCompileTime.
CoeffReturnType w () const inline inherited
equivalent to operator[](3).
CoeffReturnType x () const inline inherited
equivalent to operator[](0).
CoeffReturnType y () const inline inherited
equivalent to operator[](1).
CoeffReturnType z () const inline inherited
equivalent to operator[](2).
The documentation for this class was generated from the following file:
DenseCoeffsBase.h