TransposeImpl< MatrixType, Dense > Class Template Reference
TransposeImpl< MatrixType, Dense > Class Template Reference
#include <Transpose.h>
Inherits type< MatrixType >.
Public Types
typedef
internal::TransposeImpl_base
< MatrixType >::type Base
typedef internal::conditional
< internal::is_lvalue
< MatrixType >::value, Scalar,
const Scalar >::type ScalarWithConstIfNotLvalue
Public Member Functions
CoeffReturnType coeff (Index row, Index col) const
CoeffReturnType coeff (Index index) const
ScalarWithConstIfNotLvalue & coeffRef (Index row, Index col)
ScalarWithConstIfNotLvalue & coeffRef (Index index)
const Scalar & coeffRef (Index row, Index col) const
const Scalar & coeffRef (Index index) const
ScalarWithConstIfNotLvalue * data ()
const Scalar * data () const
Index innerStride () const
Index outerStride () const
template<int LoadMode>
const PacketScalar packet (Index row, Index col) const
template<int LoadMode>
const PacketScalar packet (Index index) const
template<int LoadMode>
void writePacket (Index row, Index col, const PacketScalar &x)
template<int LoadMode>
void writePacket (Index index, const PacketScalar &x)
template<typename MatrixType>
class Eigen::TransposeImpl< MatrixType, Dense >
Member Typedef Documentation
typedef internal::TransposeImpl_base<MatrixType>::type Base
typedef internal::conditional< internal::is_lvalue<MatrixType>::value, Scalar, const Scalar >::type ScalarWithConstIfNotLvalue
Member Function Documentation
CoeffReturnType coeff (Index row, Index col) const [inline]
CoeffReturnType coeff (Index index) const [inline]
ScalarWithConstIfNotLvalue& coeffRef (Index row, Index col) [inline]
References EIGEN_STATIC_ASSERT_LVALUE.
ScalarWithConstIfNotLvalue& coeffRef (Index index) [inline]
References EIGEN_STATIC_ASSERT_LVALUE.
const Scalar& coeffRef (Index row, Index col) const [inline]
const Scalar& coeffRef (Index index) const [inline]
ScalarWithConstIfNotLvalue* data () [inline]
const Scalar* data () const [inline]
Index innerStride () const [inline]
Index outerStride () const [inline]
const PacketScalar packet (Index row, Index col) const [inline]
References col(), and row().
const PacketScalar packet (Index index) const [inline]
void writePacket (Index row, Index col, const PacketScalar & x) [inline]
References col(), and row().
void writePacket (Index index, const PacketScalar & x) [inline]
The documentation for this class was generated from the following file:
Transpose.h