PastixBase< Derived > Class Template Reference
PastixBase< Derived > Class Template Reference
#include <PaStiXSupport.h>
Inherits noncopyable.
Public Types
typedef
internal::pastix_traits
< Derived >::MatrixType _MatrixType
typedef SparseMatrix< Scalar,
ColMajor > ColSpMatrix
typedef MatrixType::Index Index
typedef _MatrixType MatrixType
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Scalar Scalar
typedef Matrix< Scalar,
Dynamic, 1 > Vector
Public Member Functions
template<typename Rhs , typename Dest >
bool _solve (const MatrixBase< Rhs > &b, MatrixBase< Dest > &x) const
template<typename Rhs , typename DestScalar , int DestOptions, typename DestIndex >
void _solve_sparse (const Rhs &b, SparseMatrix< DestScalar, DestOptions, DestIndex > &dest) const
Index cols () const
Derived & derived ()
const Derived & derived () const
Array< RealScalar, IPARM_SIZE, 1 > & dparm ()
double & dparm (int idxparam)
ComputationInfo info () const
Reports whether previous computation was successful.
Array< Index, IPARM_SIZE, 1 > & iparm ()
int & iparm (int idxparam)
PastixBase ()
Index rows () const
template<typename Rhs >
const internal::solve_retval
< PastixBase, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const
internal::sparse_solve_retval
< PastixBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
~PastixBase ()
Protected Member Functions
void analyzePattern (ColSpMatrix &mat)
void clean ()
void compute (ColSpMatrix &mat)
void factorize (ColSpMatrix &mat)
void init ()
Protected Attributes
int m_analysisIsOk
int m_comm
Matrix< double, DPARM_SIZE, 1 > m_dparm
int m_factorizationIsOk
ComputationInfo m_info
int m_initisOk
Matrix< Index, Dynamic, 1 > m_invp
Matrix< int, IPARM_SIZE, 1 > m_iparm
bool m_isInitialized
pastix_data_t * m_pastixdata
Matrix< Index, Dynamic, 1 > m_perm
int m_size
template<class Derived>
class Eigen::PastixBase< Derived >
Member Typedef Documentation
typedef internal::pastix_traits<Derived>::MatrixType _MatrixType
typedef SparseMatrix<Scalar, ColMajor> ColSpMatrix
Reimplemented in PastixLDLT< _MatrixType, _UpLo >, PastixLLT< _MatrixType, _UpLo >, and PastixLU< _MatrixType, IsStrSym >.
typedef MatrixType::Index Index
Reimplemented in PastixLU< _MatrixType, IsStrSym >.
typedef _MatrixType MatrixType
Reimplemented in PastixLDLT< _MatrixType, _UpLo >, PastixLLT< _MatrixType, _UpLo >, and PastixLU< _MatrixType, IsStrSym >.
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::Scalar Scalar
typedef Matrix<Scalar,Dynamic,1> Vector
Constructor & Destructor Documentation
PastixBase () [inline]
~PastixBase () [inline]
Member Function Documentation
bool _solve (const MatrixBase< Rhs > & b, MatrixBase< Dest > & x) const
References eigen_assert, Eigen::internal::eigen_pastix(), EIGEN_STATIC_ASSERT, Eigen::NumericalIssue, Eigen::RowMajorBit, and Eigen::Success.
void _solve_sparse (const Rhs & b, SparseMatrix< DestScalar, DestOptions, DestIndex > & dest) const [inline]
void analyzePattern (ColSpMatrix & mat) [protected]
References eigen_assert, Eigen::internal::eigen_pastix(), SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::NumericalIssue, SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), SparseMatrix< _Scalar, _Options, _Index >::rows(), Eigen::Success, and SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by PastixLU< _MatrixType, IsStrSym >::analyzePattern(), PastixLLT< _MatrixType, _UpLo >::analyzePattern(), and PastixLDLT< _MatrixType, _UpLo >::analyzePattern().
void clean () [inline, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::~PastixBase().
Index cols (void) const [inline]
void compute (ColSpMatrix & mat) [protected]
References SparseMatrix< _Scalar, _Options, _Index >::cols(), eigen_assert, and SparseMatrix< _Scalar, _Options, _Index >::rows().
Referenced by PastixLU< _MatrixType, IsStrSym >::compute(), PastixLLT< _MatrixType, _UpLo >::compute(), and PastixLDLT< _MatrixType, _UpLo >::compute().
Derived& derived () [inline]
Referenced by PastixBase< PastixLU< _MatrixType > >::_solve_sparse().
const Derived& derived () const [inline]
Array<RealScalar,IPARM_SIZE,1>& dparm () [inline]
Returns a reference to the double vector DPARM of PaStiX parameters The statistics related to the different phases of factorization and solve are saved here as well
See also:
analyzePattern() factorize()
double& dparm (int idxparam) [inline]
Return a reference to a particular index parameter of the DPARM vector
See also:
dparm()
void factorize (ColSpMatrix & mat) [protected]
References eigen_assert, Eigen::internal::eigen_pastix(), SparseMatrix< _Scalar, _Options, _Index >::innerIndexPtr(), Eigen::NumericalIssue, SparseMatrix< _Scalar, _Options, _Index >::outerIndexPtr(), SparseMatrix< _Scalar, _Options, _Index >::rows(), Eigen::Success, and SparseMatrix< _Scalar, _Options, _Index >::valuePtr().
Referenced by PastixLU< _MatrixType, IsStrSym >::factorize(), PastixLLT< _MatrixType, _UpLo >::factorize(), and PastixLDLT< _MatrixType, _UpLo >::factorize().
ComputationInfo info () const [inline]
Reports whether previous computation was successful.
Returns:
Success if computation was succesful, NumericalIssue if the PaStiX reports a problem InvalidInput if the input matrix is invalid
See also:
iparm()
void init () [protected]
Initialize the PaStiX data structure. *A first call to this function fills iparm and dparm with the default PaStiX parameters
See also:
iparm() dparm()
Reimplemented in PastixLDLT< _MatrixType, _UpLo >, PastixLLT< _MatrixType, _UpLo >, and PastixLU< _MatrixType, IsStrSym >.
References Eigen::internal::eigen_pastix(), Eigen::InvalidInput, and Eigen::Success.
Referenced by PastixBase< PastixLU< _MatrixType > >::PastixBase().
Array<Index,IPARM_SIZE,1>& iparm () [inline]
Returns a reference to the integer vector IPARM of PaStiX parameters to modify the default parameters. The statistics related to the different phases of factorization and solve are saved here as well
See also:
analyzePattern() factorize()
int& iparm (int idxparam) [inline]
Return a reference to a particular index parameter of the IPARM vector
See also:
iparm()
Index rows (void) const [inline]
Referenced by PastixBase< PastixLU< _MatrixType > >::_solve_sparse(), and PastixBase< PastixLU< _MatrixType > >::solve().
const internal::solve_retval<PastixBase, Rhs> solve (const MatrixBase< Rhs > & b) const [inline]
Returns:
the solution x of using the current decomposition of A.
See also:
compute()
const internal::sparse_solve_retval<PastixBase, Rhs> solve (const SparseMatrixBase< Rhs > & b) const [inline]
Returns:
the solution x of using the current decomposition of A.
See also:
compute()
Member Data Documentation
int m_analysisIsOk [protected]
int m_comm [mutable, protected]
Matrix<double,DPARM_SIZE,1> m_dparm [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean(), and PastixBase< PastixLU< _MatrixType > >::dparm().
int m_factorizationIsOk [protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::_solve_sparse().
ComputationInfo m_info [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::info().
int m_initisOk [protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean().
Matrix<Index,Dynamic,1> m_invp [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean().
Matrix<int,IPARM_SIZE,1> m_iparm [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean(), and PastixBase< PastixLU< _MatrixType > >::iparm().
bool m_isInitialized [protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::info(), and PastixBase< PastixLU< _MatrixType > >::solve().
pastix_data_t* m_pastixdata [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean().
Matrix<Index,Dynamic,1> m_perm [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::clean().
int m_size [mutable, protected]
Referenced by PastixBase< PastixLU< _MatrixType > >::cols(), and PastixBase< PastixLU< _MatrixType > >::rows().
The documentation for this class was generated from the following file:
PaStiXSupport.h