TranspositionsBase< Derived > Class Template Reference
TranspositionsBase< Derived > Class Template Reference
#include <Transpositions.h>
Public Types
typedef IndicesType::Scalar Index
typedef Traits::IndicesType IndicesType
Public Member Functions
const Index & coeff (Index i) const
Index & coeffRef (Index i)
Derived & derived ()
const Derived & derived () const
const IndicesType & indices () const
IndicesType & indices ()
Transpose< TranspositionsBase > inverse () const
const Index & operator() (Index i) const
Index & operator() (Index i)
template<typename OtherDerived >
Derived & operator= (const TranspositionsBase< OtherDerived > &other)
const Index & operator[] (Index i) const
Index & operator[] (Index i)
void resize (int size)
void setIdentity ()
Index size () const
Transpose< TranspositionsBase > transpose () const
template<typename Derived>
class Eigen::TranspositionsBase< Derived >
Member Typedef Documentation
typedef IndicesType::Scalar Index
Reimplemented in TranspositionsWrapper< _IndicesType >, Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, PacketAccess >, Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, and Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >.
typedef Traits::IndicesType IndicesType
Reimplemented in TranspositionsWrapper< _IndicesType >, Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, PacketAccess >, Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, and Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >.
Member Function Documentation
const Index& coeff (Index i) const [inline]
Direct access to the underlying index vector
Referenced by PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::operator=().
Index& coeffRef (Index i) [inline]
Direct access to the underlying index vector
Referenced by TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity().
Derived& derived () [inline]
Referenced by TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), Eigen::operator*(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess >::operator=(), and TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose().
const Derived& derived () const [inline]
const IndicesType& indices () const [inline]
const version of indices().
Reimplemented in TranspositionsWrapper< _IndicesType >, Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, PacketAccess >, Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, and Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >.
Referenced by TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::coeff(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::coeffRef(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator()(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator[](), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::resize(), TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::setIdentity(), and TranspositionsBase< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::size().
IndicesType& indices () [inline]
Returns:
a reference to the stored array representing the transpositions.
Reimplemented in TranspositionsWrapper< _IndicesType >, Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, PacketAccess >, Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, and Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >.
Transpose<TranspositionsBase> inverse () const [inline]
Returns:
the inverse transformation
const Index& operator() (Index i) const [inline]
Direct access to the underlying index vector
Index& operator() (Index i) [inline]
Direct access to the underlying index vector
Derived& operator= (const TranspositionsBase< OtherDerived > & other) [inline]
Copies the other transpositions into *this
Reimplemented in TranspositionsWrapper< _IndicesType >, Map< Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, PacketAccess >, Transpositions< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, and Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >.
Referenced by Transpositions< RowsAtCompileTime, MaxRowsAtCompileTime >::operator=(), and TranspositionsWrapper< _IndicesType >::operator=().
const Index& operator[] (Index i) const [inline]
Direct access to the underlying index vector
Index& operator[] (Index i) [inline]
Direct access to the underlying index vector
void resize (int size) [inline]
Resizes to given size.
void setIdentity () [inline]
Sets *this to represents an identity transformation
Index size () const [inline]
Returns:
the number of transpositions
Referenced by PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::operator=().
Transpose<TranspositionsBase> transpose () const [inline]
Returns:
the tranpose transformation
The documentation for this class was generated from the following file:
Transpositions.h