DenseBase< Derived > Class Template Reference
DenseBase< Derived > Class Template Reference
Core module
Base class for all dense matrices, vectors, and arrays.
#include <DenseBase.h>
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime,
MaxRowsAtCompileTime,
MaxColsAtCompileTime,
MaxSizeAtCompileTime,
IsVectorAtCompileTime,
Flags,
IsRowMajor ,
CoeffReadCost
}
typedef internal::traits
< Derived >::Index Index
The type of indices.
Public Member Functions
bool all (void) const
bool any (void) const
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows,
BlockCols > block (Index startRow, Index startCol)
template<int BlockRows, int BlockCols>
const Block< const Derived,
BlockRows, BlockCols > block (Index startRow, Index startCol) const
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomLeftCorner () const
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > bottomRightCorner () const
RowsBlockXpr bottomRows (Index n)
ConstRowsBlockXpr bottomRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type bottomRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type bottomRows () const
ColXpr col (Index i)
ConstColXpr col (Index i) const
ConstColwiseReturnType colwise () const
ColwiseReturnType colwise ()
Index count () const
EvalReturnType eval () const
void fill (const Scalar &value)
template<unsigned int Added, unsigned int Removed>
const Flagged< Derived, Added,
Removed > flagged () const
const WithFormat< Derived > format (const IOFormat &fmt) const
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type head ()
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type head () const
SegmentReturnType head (Index size)
DenseBase::ConstSegmentReturnType head (Index size) const
Index innerSize () const
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isApproxToConstant (const Scalar &value, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isConstant (const Scalar &value, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, RealScalar prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isOnes (RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
bool isZero (RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
ColsBlockXpr leftCols (Index n)
ConstColsBlockXpr leftCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type leftCols ()
template<int N>
ConstNColsBlockXpr< N >::Type leftCols () const
internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
Scalar mean () const
ColsBlockXpr middleCols (Index startCol, Index numCols)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol)
template<int N>
ConstNColsBlockXpr< N >::Type middleCols (Index startCol) const
RowsBlockXpr middleRows (Index startRow, Index numRows)
ConstRowsBlockXpr middleRows (Index startRow, Index numRows) const
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow)
template<int N>
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow) const
internal::traits< Derived >::Scalar minCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
const NestByValue< Derived > nestByValue () const
Index nonZeros () const
template<typename CustomNullaryOp >
const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
const CwiseNullaryOp
< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp &func)
CommaInitializer< Derived > operator<< (const Scalar &s)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const DenseBase< OtherDerived > &other)
Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
Index outerSize () const
Scalar prod () const
template<typename Func >
internal::result_of< Func(typename
internal::traits< Derived >
::Scalar)>::type redux (const Func &func) const
template<int RowFactor, int ColFactor>
const Replicate< Derived,
RowFactor, ColFactor > replicate () const
const Replicate< Derived,
Dynamic, Dynamic > replicate (Index rowFacor, Index colFactor) const
void resize (Index size)
void resize (Index rows, Index cols)
ReverseReturnType reverse ()
ConstReverseReturnType reverse () const
void reverseInPlace ()
ColsBlockXpr rightCols (Index n)
ConstColsBlockXpr rightCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type rightCols ()
template<int N>
ConstNColsBlockXpr< N >::Type rightCols () const
RowXpr row (Index i)
ConstRowXpr row (Index i) const
ConstRowwiseReturnType rowwise () const
RowwiseReturnType rowwise ()
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type segment (Index start)
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type segment (Index start) const
SegmentReturnType segment (Index start, Index size)
DenseBase::ConstSegmentReturnType segment (Index start, Index size) const
template<typename ThenDerived , typename ElseDerived >
const Select< Derived,
ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived,
ThenDerived, typename
ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, typename ThenDerived::Scalar elseScalar) const
template<typename ElseDerived >
const Select< Derived,
typename
ElseDerived::ConstantReturnType,
ElseDerived > select (typename ElseDerived::Scalar thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Derived & setConstant (const Scalar &value)
Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setOnes ()
Derived & setRandom ()
Derived & setZero ()
Scalar sum () const
template<typename OtherDerived >
void swap (const DenseBase< OtherDerived > &other, int=OtherDerived::ThisConstantIsPrivateInPlainObjectBase)
template<typename OtherDerived >
void swap (PlainObjectBase< OtherDerived > &other)
template<int Size>
DenseBase< Derived >::template
FixedSegmentReturnType< Size >
::Type tail ()
template<int Size>
DenseBase< Derived >::template
ConstFixedSegmentReturnType
< Size >::Type tail () const
SegmentReturnType tail (Index size)
DenseBase::ConstSegmentReturnType tail (Index size) const
Block< Derived > topLeftCorner (Index cRows, Index cCols)
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topLeftCorner () const
Block< Derived > topRightCorner (Index cRows, Index cCols)
const Block< const Derived > topRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
template<int CRows, int CCols>
const Block< const Derived,
CRows, CCols > topRightCorner () const
RowsBlockXpr topRows (Index n)
ConstRowsBlockXpr topRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type topRows ()
template<int N>
ConstNRowsBlockXpr< N >::Type topRows () const
Eigen::Transpose< Derived > transpose ()
ConstTransposeReturnType transpose () const
void transposeInPlace ()
CoeffReturnType value () const
template<typename Visitor >
void visit (Visitor &func) const
Static Public Member Functions
static const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static const ConstantReturnType Constant (Index size, const Scalar &value)
static const ConstantReturnType Constant (const Scalar &value)
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const
RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const ConstantReturnType Ones (Index rows, Index cols)
static const ConstantReturnType Ones (Index size)
static const ConstantReturnType Ones ()
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index rows, Index cols)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random (Index size)
static const CwiseNullaryOp
< internal::scalar_random_op
< Scalar >, Derived > Random ()
static const ConstantReturnType Zero (Index rows, Index cols)
static const ConstantReturnType Zero (Index size)
static const ConstantReturnType Zero ()
Protected Member Functions
DenseBase ()
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See Also
The class hierarchy
Member Typedef Documentation
typedef internal::traits<Derived>::Index Index
The type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See Also
Preprocessor directives.
Member Enumeration Documentation
anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See Also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See Also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Constructor & Destructor Documentation
DenseBase () inline protected
Default constructor. Do nothing.
References DenseBase< Derived >::IsRowMajor, DenseBase< Derived >::MaxColsAtCompileTime, and DenseBase< Derived >::MaxRowsAtCompileTime.
Member Function Documentation
bool all (void) const inline
Returns
true if all coefficients are true
Example:
Vector3f boxMin(Vector3f::Zero()), boxMax(Vector3f::Ones());
Vector3f p0 = Vector3f::Random(), p1 = Vector3f::Random().cwiseAbs();
// let's check if p0 and p1 are inside the axis aligned box defined by the corners boxMin,boxMax:
cout << "Is (" << p0.transpose() << ") inside the box: "
     << ((boxMin.array()<p0.array()).all() && (boxMax.array()>p0.array()).all()) << endl;
cout << "Is (" << p1.transpose() << ") inside the box: "
     << ((boxMin.array()<p1.array()).all() && (boxMax.array()>p1.array()).all()) << endl;
Output:
Is (0.68 -0.211  0.566) inside the box: 0
Is (0.597 0.823 0.605) inside the box: 1
See Also
any(), Cwise::operator<()
References Eigen::Dynamic.
bool any (void) const inline
Returns
true if at least one coefficient is true
See Also
all()
References Eigen::Dynamic.
Block<Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block(1, 1, 2, 2):" << endl << m.block(1, 1, 2, 2) << endl;
m.block(1, 1, 2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block(1, 1, 2, 2):
-6 1
-3 0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
const Block<const Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block(Index,Index,Index,Index).
Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block<2,2>(1,1):" << endl << m.block<2,2>(1,1) << endl;
m.block<2,2>(1,1).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block<2,2>(1,1):
-6 1
-3 0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index).
Block<Derived> bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner(2, 2):" << endl;
cout << m.bottomLeftCorner(2, 2) << endl;
m.bottomLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner(2, 2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner(Index, Index).
Block<Derived, CRows, CCols> bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,2>():" << endl;
cout << m.bottomLeftCorner<2,2>() << endl;
m.bottomLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,2>():
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
Block<Derived> bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner(2, 2):" << endl;
cout << m.bottomRightCorner(2, 2) << endl;
m.bottomRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner(2, 2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner(Index, Index).
Block<Derived, CRows, CCols> bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,2>():" << endl;
cout << m.bottomRightCorner<2,2>() << endl;
m.bottomRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,2>():
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
References DenseBase< Derived >::IsRowMajor, and DenseBase< Derived >::IsVectorAtCompileTime.
RowsBlockXpr bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows(2):" << endl;
cout << a.bottomRows(2) << endl;
a.bottomRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows(2):
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
References DenseBase< Derived >::tail().
ConstRowsBlockXpr bottomRows (Index n) const inline
This is the const version of bottomRows(Index).
NRowsBlockXpr<N>::Type bottomRows () inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows<2>():" << endl;
cout << a.bottomRows<2>() << endl;
a.bottomRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows<2>():
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type bottomRows () const inline
This is the const version of bottomRows<int>().
ColXpr col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.col(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 4 0
0 5 0
0 6 1
See Also
row(), class Block
Referenced by VectorwiseOp< ExpressionType, Direction >::cross().
ConstColXpr col (Index i) const inline
This is the const version of col().
const DenseBase< Derived >::ConstColwiseReturnType colwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each column:" << endl << m.colwise().sum() << endl;
cout << "Here is the maximum absolute value of each column:"
     << endl << m.cwiseAbs().colwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each column:
  1.04  0.815 -0.238
Here is the maximum absolute value of each column:
 0.68 0.823 0.536
See Also
rowwise(), class VectorwiseOp, Tutorial page 7 - Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
DenseBase< Derived >::ColwiseReturnType colwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
rowwise(), class VectorwiseOp, Tutorial page 7 - Reductions, visitors and broadcasting
const DenseBase< Derived >::ConstantReturnType Constant (Index rows, Index cols, const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const DenseBase< Derived >::ConstantReturnType Constant (Index size, const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const DenseBase< Derived >::ConstantReturnType Constant (const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
DenseBase< Derived >::Index count () const inline
Returns
the number of coefficients which evaluate to true
See Also
all(), any()
EvalReturnType eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
void fill (const Scalar & value) inline
Alias for setConstant(): sets all coefficients in this expression to value.
See Also
setConstant(), Constant(), class CwiseNullaryOp
const Flagged< Derived, Added, Removed > flagged () const inline
Returns
an expression of *this with added and removed flags
This is mostly for internal use.
See Also
class Flagged
const WithFormat< Derived > format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See Also
class IOFormat, class WithFormat
DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type head () inline
Returns
a fixed-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
The template parameter Size is the number of coefficients in the block
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head<2>() << endl;
v.head<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
See Also
class Block
DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type head () const inline
This is the const version of head<int>().
DenseBase< Derived >::SegmentReturnType head (Index size) inline
Returns
a dynamic-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
size the number of coefficients in the block
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head(2) << endl;
v.head(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
DenseBase< Derived >::ConstSegmentReturnType head (Index size) const inline
This is the const version of head(Index).
Index innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
bool isApprox (const DenseBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See Also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
Referenced by Transform< Scalar, Dim, Mode, _Options >::isApprox().
bool isApproxToConstant (const Scalar & value, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
bool isConstant (const Scalar & value, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, RealScalar prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See Also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
bool isMuchSmallerThan (const DenseBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See Also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
bool isOnes (RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Ones();
m(0,2) += 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isOnes() returns: " << m.isOnes() << endl;
cout << "m.isOnes(1e-3) returns: " << m.isOnes(1e-3) << endl;
Output:
Here's the matrix m:
1 1 1
1 1 1
1 1 1
m.isOnes() returns: 0
m.isOnes(1e-3) returns: 1
See Also
class CwiseNullaryOp, Ones()
bool isZero (RealScalar prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Zero();
m(0,2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isZero() returns: " << m.isZero() << endl;
cout << "m.isZero(1e-3) returns: " << m.isZero(1e-3) << endl;
Output:
Here's the matrix m:
     0      0 0.0001
     0      0      0
     0      0      0
m.isZero() returns: 0
m.isZero(1e-3) returns: 1
See Also
class CwiseNullaryOp, Zero()
ColsBlockXpr leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols(2):" << endl;
cout << a.leftCols(2) << endl;
a.leftCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols(2):
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr leftCols (Index n) const inline
This is the const version of leftCols(Index).
NColsBlockXpr<N>::Type leftCols () inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols<2>():" << endl;
cout << a.leftCols<2>() << endl;
a.leftCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols<2>():
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type leftCols () const inline
This is the const version of leftCols<int>().
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See Also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp
internal::traits< Derived >::Scalar maxCoeff () const inline
Returns
the maximum of all coefficients of *this
internal::traits< Derived >::Scalar maxCoeff (IndexType * row, IndexType * col) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
internal::traits< Derived >::Scalar maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
See Also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
internal::traits< Derived >::Scalar mean () const inline
Returns
the mean of all coefficients of *this
See Also
trace(), prod(), sum()
ColsBlockXpr middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleCols(1,3) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const inline
This is the const version of middleCols(Index,Index).
NColsBlockXpr<N>::Type middleCols (Index startCol) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block
Parameters
startCol the index of the first column in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(:,1..3) =\n" << A.middleCols<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(:,1..3) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type middleCols (Index startCol) const inline
This is the const version of middleCols<int>().
RowsBlockXpr middleRows (Index startRow, Index numRows) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
numRows the number of rows in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(2..3,:) =\n" << A.middleRows(2,2) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(2..3,:) =
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr middleRows (Index startRow, Index numRows) const inline
This is the const version of middleRows(Index,Index).
NRowsBlockXpr<N>::Type middleRows (Index startRow) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block
Parameters
startRow the index of the first row in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleRows<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-2 -3  3  3 -5
 6  6 -3  5 -8
 6 -5  0 -8  6
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type middleRows (Index startRow) const inline
This is the const version of middleRows<int>().
internal::traits< Derived >::Scalar minCoeff () const inline
Returns
the minimum of all coefficients of *this
internal::traits< Derived >::Scalar minCoeff (IndexType * row, IndexType * col) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
See Also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visitor(), DenseBase::minCoeff()
internal::traits< Derived >::Scalar minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
See Also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::minCoeff()
const NestByValue< Derived > nestByValue () const inline
Returns
an expression of the temporary version of *this.
Index nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
const CwiseNullaryOp<CustomNullaryOp, Derived> NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) inline
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const CwiseNullaryOp<CustomNullaryOp, Derived> NullaryExpr (Index size, const CustomNullaryOp & func) inline
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const CwiseNullaryOp<CustomNullaryOp, Derived> NullaryExpr (const CustomNullaryOp & func) inline
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See Also
class CwiseNullaryOp
const DenseBase< Derived >::ConstantReturnType Ones (Index rows, Index cols) inline static
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
cout << MatrixXi::Ones(2,3) << endl;
Output:
1 1 1
1 1 1
See Also
Ones(), Ones(Index), isOnes(), class Ones
const DenseBase< Derived >::ConstantReturnType Ones (Index size) inline static
Returns
an expression of a vector where all coefficients equal one.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
cout << 6 * RowVectorXi::Ones(4) << endl;
cout << VectorXf::Ones(2) << endl;
Output:
6 6 6 6
1
1
See Also
Ones(), Ones(Index,Index), isOnes(), class Ones
const DenseBase< Derived >::ConstantReturnType Ones () inline static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Ones() << endl;
cout << 6 * RowVector4i::Ones() << endl;
Output:
1 1
1 1
6 6 6 6
See Also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
CommaInitializer< Derived > operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Matrix3i m1;
m1 << 1, 2, 3,
      4, 5, 6,
      7, 8, 9;
cout << m1 << endl << endl;
Matrix3i m2 = Matrix3i::Identity();
m2.block(0,0, 2,2) << 10, 11, 12, 13;
cout << m2 << endl << endl;
Vector2i v1;
v1 << 14, 15;
m2 << v1.transpose(), 16,
      v1, m1.block(1,1,2,2);
cout << m2 << endl;
Output:
1 2 3
4 5 6
7 8 9
10 11  0
12 13  0
 0  0  1
14 15 16
14  5  6
15  8  9
See Also
CommaInitializer::finished(), class CommaInitializer
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > & other) inline
See Also
operator<<(const Scalar&)
Derived & operator= (const DenseBase< OtherDerived > & other) inline
Copies other into *this.
Returns
a reference to *this.
Derived & operator= (const DenseBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
Derived & operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
References EigenBase< Derived >::derived().
Index outerSize () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
References DenseBase< Derived >::IsRowMajor, and DenseBase< Derived >::IsVectorAtCompileTime.
internal::traits< Derived >::Scalar prod () const inline
Returns
the product of all coefficients of *this
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the product of all the coefficients:" << endl << m.prod() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the product of all the coefficients:
0.0019
See Also
sum(), mean(), trace()
References Eigen::Dynamic.
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index rows, Index cols) inline static
Returns
a random matrix expression
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
cout << MatrixXi::Random(2,3) << endl;
Output:
 7  6  9
-2  6 -6
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index), MatrixBase::Random()
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index size) inline static
Returns
a random vector expression
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
cout << VectorXi::Random(2) << endl;
Output:
7
-2
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random()
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random () inline static
Returns
a fixed-size random matrix or vector expression
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << 100 * Matrix2i::Random() << endl;
Output:
700 600
-200 600
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See Also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random(Index)
internal::result_of<Func(typename internal::traits<Derived>::Scalar)>::type redux (const Func & func) const inline
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current STL and TR1 functor styles are handled.
See Also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
const Replicate< Derived, RowFactor, ColFactor > replicate () const inline
Returns
an expression of the replication of *this
Example:
MatrixXi m = MatrixXi::Random(2,3);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "m.replicate<3,2>() = ..." << endl;
cout << m.replicate<3,2>() << endl;
Output:
Here is the matrix m:
 7  6  9
-2  6 -6
m.replicate<3,2>() = ...
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
See Also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Vector3i v = Vector3i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "v.replicate(2,5) = ..." << endl;
cout << v.replicate(2,5) << endl;
Output:
Here is the vector v:
7
-2
6
v.replicate(2,5) = ...
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
See Also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
void resize (Index size) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
void resize (Index rows, Index cols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
DenseBase< Derived >::ReverseReturnType reverse () inline
Returns
an expression of the reverse of *this.
Example:
MatrixXi m = MatrixXi::Random(3,4);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the reverse of m:" << endl << m.reverse() << endl;
cout << "Here is the coefficient (1,0) in the reverse of m:" << endl
     << m.reverse()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 4." << endl;
m.reverse()(1,0) = 4;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  6 -3  1
-2  9  6  0
 6 -6 -5  3
Here is the reverse of m:
 3 -5 -6  6
 0  6  9 -2
 1 -3  6  7
Here is the coefficient (1,0) in the reverse of m:
0
Let us overwrite this coefficient with the value 4.
Now the matrix m is:
 7  6 -3  1
-2  9  6  4
 6 -6 -5  3
const DenseBase< Derived >::ConstReverseReturnType reverse () const inline
This is the const version of reverse().
void reverseInPlace () inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional features:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API allows to avoid creating a temporary (the current implementation creates a temporary, but that could be avoided using swap)
it allows future optimizations (cache friendliness, etc.)
See Also
reverse()
ColsBlockXpr rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols(2):" << endl;
cout << a.rightCols(2) << endl;
a.rightCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols(2):
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstColsBlockXpr rightCols (Index n) const inline
This is the const version of rightCols(Index).
NColsBlockXpr<N>::Type rightCols () inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols<2>():" << endl;
cout << a.rightCols<2>() << endl;
a.rightCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols<2>():
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See Also
class Block, block(Index,Index,Index,Index)
ConstNColsBlockXpr<N>::Type rightCols () const inline
This is the const version of rightCols<int>().
RowXpr row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.row(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 0 0
4 5 6
0 0 1
See Also
col(), class Block
Referenced by VectorwiseOp< ExpressionType, Direction >::cross(), and Transform< Scalar, Dim, Mode, _Options >::pretranslate().
ConstRowXpr row (Index i) const inline
This is the const version of row().
const DenseBase< Derived >::ConstRowwiseReturnType rowwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each row:" << endl << m.rowwise().sum() << endl;
cout << "Here is the maximum absolute value of each row:"
     << endl << m.cwiseAbs().rowwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each row:
0.948
1.15
-0.483
Here is the maximum absolute value of each row:
0.68
0.823
0.605
See Also
colwise(), class VectorwiseOp, Tutorial page 7 - Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
DenseBase< Derived >::RowwiseReturnType rowwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See Also
colwise(), class VectorwiseOp, Tutorial page 7 - Reductions, visitors and broadcasting
DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type segment (Index start) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
The template parameter Size is the number of coefficients in the block
Parameters
start the index of the first element of the sub-vector
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment<2>(1):" << endl << v.segment<2>(1) << endl;
v.segment<2>(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment<2>(1):
-2 6
Now the vector v is:
 7 -2  0  0
See Also
class Block
DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type segment (Index start) const inline
This is the const version of segment<int>(Index).
DenseBase< Derived >::SegmentReturnType segment (Index start, Index size) inline
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
start the first coefficient in the segment
size the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment(1, 2):" << endl << v.segment(1, 2) << endl;
v.segment(1, 2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment(1, 2):
-2 6
Now the vector v is:
7 0 0 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, segment(Index)
DenseBase< Derived >::ConstSegmentReturnType segment (Index start, Index size) const inline
This is the const version of segment(Index,Index).
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
MatrixXi m(3, 3);
m << 1, 2, 3,
     4, 5, 6,
     7, 8, 9;
m = (m.array() >= 5).select(-m, m);
cout << m << endl;
Output:
 1  2  3
 4 -5 -6
-7 -8 -9
See Also
class Select
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > & thenMatrix, typename ThenDerived::Scalar elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (typename ElseDerived::Scalar thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See Also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
Derived & setConstant (const Scalar & value) inline
Sets all coefficients in this expression to value.
See Also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
Derived & setLinSpaced (Index size, const Scalar & low, const Scalar & high) inline
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
VectorXf v;
v.setLinSpaced(5,0.5f,1.5f).transpose();
cout << v << endl;
Output:
0.5
0.75
1
1.25
1.5
See Also
CwiseNullaryOp
Derived & setLinSpaced (const Scalar & low, const Scalar & high) inline
Sets a linearly space vector.
The function fill *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See Also
setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
Derived & setOnes () inline
Sets all coefficients in this expression to one.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setOnes();
cout << m << endl;
Output:
 7  9 -5 -3
 1  1  1  1
 6 -3  0  9
 6  6  3  9
See Also
class CwiseNullaryOp, Ones()
Derived & setRandom () inline
Sets all coefficients in this expression to random values.
Example:
Matrix4i m = Matrix4i::Zero();
m.col(1).setRandom();
cout << m << endl;
Output:
 0  7  0  0
 0 -2  0  0
 0  6  0  0
 0  6  0  0
See Also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
Derived & setZero () inline
Sets all coefficients in this expression to zero.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setZero();
cout << m << endl;
Output:
 7  9 -5 -3
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class CwiseNullaryOp, Zero()
internal::traits< Derived >::Scalar sum () const inline
Returns
the sum of all coefficients of *this
See Also
trace(), prod(), mean()
References Eigen::Dynamic.
void swap (const DenseBase< OtherDerived > & other, int = OtherDerived::ThisConstantIsPrivateInPlainObjectBase) inline
swaps *this with the expression other.
void swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
DenseBase<Derived>::template FixedSegmentReturnType<Size>::Type tail () inline
Returns
a fixed-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
The template parameter Size is the number of coefficients in the block
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail<2>() << endl;
v.tail<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
See Also
class Block
DenseBase<Derived>::template ConstFixedSegmentReturnType<Size>::Type tail () const inline
This is the const version of tail<int>.
DenseBase< Derived >::SegmentReturnType tail (Index size) inline
Returns
a dynamic-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
size the number of coefficients in the block
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail(2) << endl;
v.tail(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See Also
class Block, block(Index,Index)
Referenced by DenseBase< Derived >::bottomRows().
DenseBase< Derived >::ConstSegmentReturnType tail (Index size) const inline
This is the const version of tail(Index).
Block<Derived> topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner(2, 2):" << endl;
cout << m.topLeftCorner(2, 2) << endl;
m.topLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner(2, 2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner(Index, Index).
Block<Derived, CRows, CCols> topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,2>():" << endl;
cout << m.topLeftCorner<2,2>() << endl;
m.topLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,2>():
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
Block<Derived> topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner(2, 2):" << endl;
cout << m.topRightCorner(2, 2) << endl;
m.topRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner(2, 2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived> topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner(Index, Index).
Block<Derived, CRows, CCols> topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,2>():" << endl;
cout << m.topRightCorner<2,2>() << endl;
m.topRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,2>():
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
const Block<const Derived, CRows, CCols> topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
RowsBlockXpr topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows(2):" << endl;
cout << a.topRows(2) << endl;
a.topRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows(2):
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstRowsBlockXpr topRows (Index n) const inline
This is the const version of topRows(Index).
NRowsBlockXpr<N>::Type topRows () inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows<2>():" << endl;
cout << a.topRows<2>() << endl;
a.topRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows<2>():
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See Also
class Block, block(Index,Index,Index,Index)
ConstNRowsBlockXpr<N>::Type topRows () const inline
This is the const version of topRows<int>().
Transpose< Derived > transpose () inline
Returns
an expression of the transpose of *this.
Example:
Matrix2i m = Matrix2i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the transpose of m:" << endl << m.transpose() << endl;
cout << "Here is the coefficient (1,0) in the transpose of m:" << endl
     << m.transpose()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 0." << endl;
m.transpose()(1,0) = 0;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
7 6
-2 6
Here is the transpose of m:
 7 -2
 6  6
Here is the coefficient (1,0) in the transpose of m:
6
Let us overwrite this coefficient with the value 0.
Now the matrix m is:
7 0
-2 6
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See Also
transposeInPlace(), adjoint()
const DenseBase< Derived >::ConstTransposeReturnType transpose () const inline
This is the const version of transpose().
Make sure you read the warning for transpose() !
See Also
transposeInPlace(), adjoint()
void transposeInPlace () inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix.
See Also
transpose(), adjoint(), adjointInPlace()
CoeffReturnType value () const inline
Returns
the unique coefficient of a 1x1 expression
void visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See Also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
References Eigen::Dynamic.
const DenseBase< Derived >::ConstantReturnType Zero (Index rows, Index cols) inline static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
cout << MatrixXi::Zero(2,3) << endl;
Output:
0 0 0
0 0 0
See Also
Zero(), Zero(Index)
const DenseBase< Derived >::ConstantReturnType Zero (Index size) inline static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
cout << RowVectorXi::Zero(4) << endl;
cout << VectorXf::Zero(2) << endl;
Output:
0 0 0 0
0
0
See Also
Zero(), Zero(Index,Index)
const DenseBase< Derived >::ConstantReturnType Zero () inline static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Zero() << endl;
cout << RowVector4i::Zero() << endl;
Output:
0 0
0 0
0 0 0 0
See Also
Zero(Index), Zero(Index,Index)
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See Also
DenseBase::format()
The documentation for this class was generated from the following files:
DenseBase.h
BlockMethods.h
Assign.h
BooleanRedux.h
CommaInitializer.h
CwiseNullaryOp.h
EigenBase.h
Flagged.h
Fuzzy.h
IO.h
NestByValue.h
Random.h
Redux.h
Replicate.h
ReturnByValue.h
Reverse.h
Select.h
SelfCwiseBinaryOp.h
Transpose.h
VectorBlock.h
VectorwiseOp.h
Visitor.h