TriangularBase< Derived > Class Template Reference
TriangularBase< Derived > Class Template Reference
#include <TriangularMatrix.h>
Public Types
enum {
Mode,
CoeffReadCost,
RowsAtCompileTime,
ColsAtCompileTime,
MaxRowsAtCompileTime,
MaxColsAtCompileTime
}
typedef internal::traits
< Derived >::DenseMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef internal::traits
< Derived >::Index Index
typedef internal::traits
< Derived >::Scalar Scalar
typedef internal::traits
< Derived >::StorageKind StorageKind
Public Member Functions
template<typename Dest >
void addTo (Dest &dst) const
template<typename Dest >
void applyThisOnTheLeft (Dest &dst) const
template<typename Dest >
void applyThisOnTheRight (Dest &dst) const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
Index cols () const
Derived & const_cast_derived () const
const Derived & const_derived () const
template<typename Other >
void copyCoeff (Index row, Index col, Other &other)
Derived & derived ()
const Derived & derived () const
template<typename Dest >
void evalTo (Dest &dst) const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void evalToLazy (MatrixBase< DenseDerived > &other) const
Index innerStride () const
Scalar operator() (Index row, Index col) const
Scalar & operator() (Index row, Index col)
Index outerStride () const
Index rows () const
Index size () const
template<typename Dest >
void subTo (Dest &dst) const
DenseMatrixType toDenseMatrix () const
TriangularBase ()
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
template<typename Derived>
class Eigen::TriangularBase< Derived >
Member Typedef Documentation
typedef internal::traits<Derived>::DenseMatrixType DenseMatrixType
Reimplemented in TriangularView< _MatrixType, _Mode >.
typedef DenseMatrixType DenseType
typedef internal::traits<Derived>::Index Index
Reimplemented from EigenBase< Derived >.
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
typedef internal::traits<Derived>::Scalar Scalar
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
typedef internal::traits<Derived>::StorageKind StorageKind
Reimplemented from EigenBase< Derived >.
Reimplemented in TriangularView< _MatrixType, _Mode >.
Member Enumeration Documentation
anonymous enum
Enumerator:
Mode
CoeffReadCost
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
Constructor & Destructor Documentation
TriangularBase () [inline]
Member Function Documentation
void addTo (Dest & dst) const [inline, inherited]
void applyThisOnTheLeft (Dest & dst) const [inline, inherited]
Reimplemented in HouseholderSequence< VectorsType, CoeffsType, Side >.
void applyThisOnTheRight (Dest & dst) const [inline, inherited]
Reimplemented in HouseholderSequence< VectorsType, CoeffsType, Side >.
void check_coordinates (Index row, Index col) const [inline, protected]
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
void check_coordinates_internal (Index , Index) const [inline, protected]
Referenced by TriangularView< _MatrixType, _Mode >::coeff(), and TriangularView< _MatrixType, _Mode >::coeffRef().
Scalar coeff (Index row, Index col) const [inline]
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
Scalar& coeffRef (Index row, Index col) [inline]
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::operator()().
Index cols (void) const [inline]
Returns:
the number of columns.
See also:
rows(), ColsAtCompileTime
Reimplemented from EigenBase< Derived >.
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::check_coordinates(), TriangularView< _MatrixType, _Mode >::lazyAssign(), TriangularView< _MatrixType, _Mode >::operator=(), and TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
Derived& const_cast_derived () const [inline, inherited]
Referenced by SparseVector< _Scalar, _Options, _Index >::operator=(), and SparseMatrix< Scalar, RowMajor >::operator=().
const Derived& const_derived () const [inline, inherited]
void copyCoeff (Index row, Index col, Other & other) [inline]
See also:
MatrixBase::copyCoeff(row,col)
Derived& derived () [inline, inherited]
Returns:
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::applyThisOnTheLeft(), EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::applyThisOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::assign(), SparseVector< _Scalar, _Options, _Index >::assign(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::assignGeneric(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::coeff(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::coeffRef(), EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::cols(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::copyCoeff(), SparseMatrixBase< Derived >::dot(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::evalTo(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::evalTo(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::indices(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::innerStride(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::inverse(), TriangularView< _MatrixType, _Mode >::lazyAssign(), SluMatrix::Map(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::markAsRValue(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), RotationBase< Derived, 3 >::operator*(), Translation< _Scalar, _Dim >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::operator*(), SparseMatrixBase< Derived >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), DenseBase< Derived >::operator+=(), SparseMatrixBase< Derived >::operator+=(), DenseBase< Derived >::operator-=(), SparseMatrixBase< Derived >::operator-=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::operator=(), MatrixBase< Derived >::operator=(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), TriangularView< _MatrixType, _Mode >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess >::operator=(), PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), SparseMatrix< Scalar, RowMajor >::operator=(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::outerStride(), PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::rows(), TriangularBase< SelfAdjointView< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), PardisoImpl< PardisoLU< MatrixType > >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), PastixBase< PastixLU< _MatrixType > >::solve(), SparseTriangularView< MatrixType, Mode >::solveInPlace(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), SparseVector< _Scalar, _Options, _Index >::SparseVector(), TriangularView< _MatrixType, _Mode >::swap(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::toDense(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::toDenseMatrix(), Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::transpose(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::transpose(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
const Derived& derived () const [inline, inherited]
Returns:
a const reference to the derived object
void evalTo (Dest & dst) const [inline, inherited]
Reimplemented in SparseSparseProduct< LhsNested, RhsNested >.
Referenced by EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::addTo(), and EigenBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >::subTo().
void evalTo (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
References Eigen::EvalBeforeAssigningBit, and DenseBase< Derived >::swap().
void evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
References Eigen::Dynamic, EIGEN_UNROLLING_LIMIT, and DenseBase< Derived >::resize().
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
Index innerStride () const [inline]
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
Scalar operator() (Index row, Index col) const [inline]
Scalar& operator() (Index row, Index col) [inline]
Index outerStride () const [inline]
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
Index rows (void) const [inline]
Returns:
the number of rows.
See also:
cols(), RowsAtCompileTime
Reimplemented from EigenBase< Derived >.
Reimplemented in TriangularView< _MatrixType, _Mode >, and SelfAdjointView< MatrixType, UpLo >.
Referenced by TriangularBase< SelfAdjointView< MatrixType, UpLo > >::check_coordinates(), TriangularView< _MatrixType, _Mode >::lazyAssign(), TriangularView< _MatrixType, _Mode >::operator=(), and TriangularBase< SelfAdjointView< MatrixType, UpLo > >::toDenseMatrix().
Index size () const [inline, inherited]
Returns:
the number of coefficients, which is rows()*cols().
See also:
rows(), cols(), SizeAtCompileTime.
Reimplemented in SparseMatrixBase< Derived >, SparseMatrixBase< SparseMatrix< Scalar, _Options, int > >, SparseMatrixBase< SparseInnerVectorSet< SparseMatrix< _Scalar, _Options, _Index >, Size > >, SparseMatrixBase< CwiseUnaryOp< UnaryOp, MatrixType > >, SparseMatrixBase< Transpose< MatrixType > >, SparseMatrixBase< SparseDiagonalProduct< Lhs, Rhs > >, SparseMatrixBase< SparseMatrix< Scalar, _Options, _Index > >, SparseMatrixBase< CwiseUnaryView< ViewOp, MatrixType > >, SparseMatrixBase< SparseMatrix< _Scalar, _Options, _Index > >, SparseMatrixBase< SparseDenseOuterProduct< Lhs, Rhs, Tr > >, SparseMatrixBase< SparseInnerVectorSet< MatrixType, Size > >, SparseMatrixBase< MappedSparseMatrix< _Scalar, _Flags, _Index > >, SparseMatrixBase< SparseSparseProduct< LhsNested, RhsNested > >, SparseMatrixBase< SparseMatrix< Scalar, _Options, Index > >, SparseMatrixBase< SparseTriangularView< MatrixType, Mode > >, SparseMatrixBase< SparseVector< _Scalar, _Options, _Index > >, SparseMatrixBase< SparseView< MatrixType > >, SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >, PermutationBase< Derived >, PermutationBase< PermutationWrapper< _IndicesType > >, PermutationBase< Map< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >, _PacketAccess > >, PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >, and PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, Index > >.
Referenced by PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_resize_to_match().
void subTo (Dest & dst) const [inline, inherited]
DenseMatrixType toDenseMatrix () const [inline]
The documentation for this class was generated from the following file:
TriangularMatrix.h