UniformScaling< _Scalar > Class Template Reference
UniformScaling< _Scalar > Class Template Reference
#include <Scaling.h>
Public Types
typedef _Scalar Scalar
Public Member Functions
template<typename NewScalarType >
UniformScaling< NewScalarType > cast () const
const Scalar & factor () const
Scalar & factor ()
UniformScaling inverse () const
bool isApprox (const UniformScaling &other, typename NumTraits< Scalar >::Real prec=NumTraits< Scalar >::dummy_precision()) const
UniformScaling operator* (const UniformScaling &other) const
template<int Dim>
Transform< Scalar, Dim, Affine > operator* (const Translation< Scalar, Dim > &t) const
template<int Dim, int Mode, int Options>
Transform< Scalar, Dim,(int(Mode)==int(Isometry)?Affine:Mode)> operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename Derived >
internal::plain_matrix_type
< Derived >::type operator* (const MatrixBase< Derived > &other) const
template<typename Derived , int Dim>
Matrix< Scalar, Dim, Dim > operator* (const RotationBase< Derived, Dim > &r) const
UniformScaling ()
UniformScaling (const Scalar &s)
template<typename OtherScalarType >
UniformScaling (const UniformScaling< OtherScalarType > &other)
Protected Attributes
Scalar m_factor
template<typename _Scalar>
class Eigen::UniformScaling< _Scalar >
Member Typedef Documentation
typedef _Scalar Scalar
the scalar type of the coefficients
Constructor & Destructor Documentation
UniformScaling () [inline]
Default constructor without initialization.
Referenced by UniformScaling< _Scalar >::inverse(), and UniformScaling< _Scalar >::operator*().
UniformScaling (const Scalar & s) [inline, explicit]
Constructs and initialize a uniform scaling transformation
UniformScaling (const UniformScaling< OtherScalarType > & other) [inline, explicit]
Copy constructor with scalar type conversion
References UniformScaling< _Scalar >::factor(), and UniformScaling< _Scalar >::m_factor.
Member Function Documentation
UniformScaling<NewScalarType> cast () const [inline]
Returns:
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References UniformScaling< _Scalar >::m_factor.
const Scalar& factor () const [inline]
References UniformScaling< _Scalar >::m_factor.
Referenced by UniformScaling< _Scalar >::isApprox(), UniformScaling< _Scalar >::operator*(), RotationBase< Derived, 3 >::operator*(), Translation< _Scalar, _Dim >::operator*(), MatrixBase< Derived >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), and UniformScaling< _Scalar >::UniformScaling().
Scalar& factor () [inline]
References UniformScaling< _Scalar >::m_factor.
UniformScaling inverse () const [inline]
Returns:
the inverse scaling
References UniformScaling< _Scalar >::m_factor, and UniformScaling< _Scalar >::UniformScaling().
bool isApprox (const UniformScaling< _Scalar > & other, typename NumTraits< Scalar >::Real prec = NumTraits<Scalar>::dummy_precision()) const [inline]
Returns:
true if *this is approximately equal to other, within the precision determined by prec.
See also:
MatrixBase::isApprox()
References UniformScaling< _Scalar >::factor(), and UniformScaling< _Scalar >::m_factor.
UniformScaling operator* (const UniformScaling< _Scalar > & other) const [inline]
Concatenates two uniform scaling
References UniformScaling< _Scalar >::factor(), UniformScaling< _Scalar >::m_factor, and UniformScaling< _Scalar >::UniformScaling().
Transform< Scalar, Dim, Affine > operator* (const Translation< Scalar, Dim > & t) const [inline]
Concatenates a uniform scaling and a translation
References Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Transform< _Scalar, _Dim, _Mode, _Options >::translation(), and Translation< _Scalar, _Dim >::vector().
Transform<Scalar,Dim,(int(Mode)==int(Isometry)?Affine:Mode)> operator* (const Transform< Scalar, Dim, Mode, Options > & t) const [inline]
Concatenates a uniform scaling and an affine transformation
References UniformScaling< _Scalar >::factor(), and Transform< _Scalar, _Dim, _Mode, _Options >::prescale().
internal::plain_matrix_type<Derived>::type operator* (const MatrixBase< Derived > & other) const [inline]
Concatenates a uniform scaling and a linear transformation matrix
References UniformScaling< _Scalar >::m_factor.
Matrix<Scalar,Dim,Dim> operator* (const RotationBase< Derived, Dim > & r) const [inline]
References UniformScaling< _Scalar >::m_factor, and RotationBase< Derived, _Dim >::toRotationMatrix().
Member Data Documentation
Scalar m_factor [protected]
Referenced by UniformScaling< _Scalar >::cast(), UniformScaling< _Scalar >::factor(), UniformScaling< _Scalar >::inverse(), UniformScaling< _Scalar >::isApprox(), UniformScaling< _Scalar >::operator*(), and UniformScaling< _Scalar >::UniformScaling().
The documentation for this class was generated from the following file:
Scaling.h