SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > Class Template Reference
SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > Class Template Reference
Core module
#include <SelfCwiseBinaryOp.h>
Inherits type< SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs > >.
Public Types
typedef
internal::dense_xpr_base
< SelfCwiseBinaryOp >::type Base
typedef
internal::packet_traits
< Scalar >::type Packet
Public Member Functions
Scalar & coeffRef (Index row, Index col)
const Scalar & coeffRef (Index row, Index col) const
Scalar & coeffRef (Index index)
const Scalar & coeffRef (Index index) const
Index cols () const
template<typename OtherDerived >
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
void copyCoeff (Index index, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > &other)
template<typename OtherDerived , int StoreMode, int LoadMode>
void copyPacket (Index index, const DenseBase< OtherDerived > &other)
const Scalar * data () const
Lhs & expression () const
const BinaryOp & functor () const
Index innerStride () const
template<typename RhsDerived >
SelfCwiseBinaryOp & lazyAssign (const DenseBase< RhsDerived > &rhs)
SelfCwiseBinaryOp & operator= (const Rhs &_rhs)
Index outerStride () const
Index rows () const
SelfCwiseBinaryOp (Lhs &xpr, const BinaryOp &func=BinaryOp())
Protected Attributes
const BinaryOp & m_functor
Lhs & m_matrix
template<typename BinaryOp, typename Lhs, typename Rhs>
class Eigen::SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >
Member Typedef Documentation
typedef internal::dense_xpr_base<SelfCwiseBinaryOp>::type Base
typedef internal::packet_traits<Scalar>::type Packet
Constructor & Destructor Documentation
SelfCwiseBinaryOp (Lhs & xpr, const BinaryOp & func = BinaryOp()) [inline]
Member Function Documentation
Scalar& coeffRef (Index row, Index col) [inline]
References EIGEN_STATIC_ASSERT_LVALUE, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
const Scalar& coeffRef (Index row, Index col) const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Scalar& coeffRef (Index index) [inline]
References EIGEN_STATIC_ASSERT_LVALUE, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
const Scalar& coeffRef (Index index) const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Index cols (void) const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Referenced by SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::lazyAssign().
void copyCoeff (Index row, Index col, const DenseBase< OtherDerived > & other) [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), eigen_internal_assert, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
void copyCoeff (Index index, const DenseBase< OtherDerived > & other) [inline]
References eigen_internal_assert, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
void copyPacket (Index row, Index col, const DenseBase< OtherDerived > & other) [inline]
References col(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), eigen_internal_assert, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix, row(), and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
void copyPacket (Index index, const DenseBase< OtherDerived > & other) [inline]
References eigen_internal_assert, SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
const Scalar* data () const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Lhs& expression () const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
const BinaryOp& functor () const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_functor.
Index innerStride () const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
SelfCwiseBinaryOp& lazyAssign (const DenseBase< RhsDerived > & rhs) [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), eigen_assert, EIGEN_CHECK_BINARY_COMPATIBILIY, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
SelfCwiseBinaryOp& operator= (const Rhs & _rhs) [inline]
Index outerStride () const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Index rows (void) const [inline]
References SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::m_matrix.
Referenced by SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::lazyAssign().
Member Data Documentation
const BinaryOp& m_functor [protected]
Referenced by SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::functor().
Lhs& m_matrix [protected]
Referenced by SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::coeffRef(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::cols(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyCoeff(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::copyPacket(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::data(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::expression(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::innerStride(), SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::outerStride(), and SelfCwiseBinaryOp< BinaryOp, Lhs, Rhs >::rows().
The documentation for this class was generated from the following file:
SelfCwiseBinaryOp.h