PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
Core module
Permutation matrix.
#include <PermutationMatrix.h>
Public Member Functions
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & applyTranspositionOnTheLeft (Index i, Index j)
PermutationMatrix
< SizeAtCompileTime,
MaxSizeAtCompileTime,
IndexType > & applyTranspositionOnTheRight (Index i, Index j)
Index cols () const
Derived & derived ()
const Derived & derived () const
const IndicesType & indices () const
IndicesType & indices ()
Transpose< PermutationBase > inverse () const
PlainPermutationType operator* (const PermutationBase< Other > &other) const
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > &other) const
template<typename Other >
PermutationMatrix & operator= (const PermutationBase< Other > &other)
template<typename Other >
PermutationMatrix & operator= (const TranspositionsBase< Other > &tr)
PermutationMatrix (int size)
template<typename OtherDerived >
PermutationMatrix (const PermutationBase< OtherDerived > &other)
template<typename Other >
PermutationMatrix (const MatrixBase< Other > &indices)
template<typename Other >
PermutationMatrix (const TranspositionsBase< Other > &tr)
void resize (Index size)
Index rows () const
void setIdentity ()
void setIdentity (Index size)
Index size () const
DenseMatrixType toDenseMatrix () const
Transpose< PermutationBase > transpose () const
Detailed Description
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType>
class Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >
Permutation matrix.
Parameters
SizeAtCompileTime the number of rows/cols, or Dynamic
MaxSizeAtCompileTime the maximum number of rows/cols, or Dynamic. This optional parameter defaults to SizeAtCompileTime. Most of the time, you should not have to specify it.
IndexType the interger type of the indices
This class represents a permutation matrix, internally stored as a vector of integers.
See Also
class PermutationBase, class PermutationWrapper, class DiagonalMatrix
Constructor & Destructor Documentation
PermutationMatrix (int size) inline
Constructs an uninitialized permutation matrix of given size.
PermutationMatrix (const PermutationBase< OtherDerived > & other) inline
Copy constructor.
PermutationMatrix (const MatrixBase< Other > & indices) inline explicit
Generic constructor from expression of the indices. The indices array has the meaning that the permutations sends each integer i to indices[i].
Warning
It is your responsibility to check that the indices array that you passes actually describes a permutation, i.e., each value between 0 and n-1 occurs exactly once, where n is the array's size.
PermutationMatrix (const TranspositionsBase< Other > & tr) inline explicit
Convert the Transpositions tr to a permutation matrix
Member Function Documentation
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheLeft (Index i, Index j) inline inherited
Multiplies *this by the transposition on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(int,int): this has linear complexity and requires a lot of branching.
See Also
applyTranspositionOnTheRight(int,int)
References EigenBase< Derived >::derived(), PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheRight (Index i, Index j) inline inherited
Multiplies *this by the transposition on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See Also
applyTranspositionOnTheLeft(int,int)
References EigenBase< Derived >::derived(), PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
Index cols (void) const inline inherited
Returns
the number of columns
References PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::imag(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), RotationBase< Derived, 3 >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), SparseMatrixBase< Derived >::operator*(), Transform< Scalar, Dim, Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), DenseBase< Derived >::operator=(), Transform< Scalar, Dim, Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), Transform< Scalar, Dim, Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
const IndicesType& indices () const inline
const version of indices().
IndicesType& indices () inline
Returns
a reference to the stored array representing the permutation.
Transpose<PermutationBase> inverse () const inline inherited
Returns
the inverse permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
References EigenBase< Derived >::derived().
PlainPermutationType operator* (const PermutationBase< Other > & other) const inline inherited
Returns
the product permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
References EigenBase< Derived >::derived().
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > & other) const inline inherited
Returns
the product of a permutation with another inverse permutation.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
PermutationMatrix& operator= (const PermutationBase< Other > & other) inline
Copies the other permutation into *this
PermutationMatrix& operator= (const TranspositionsBase< Other > & tr) inline
Assignment from the Transpositions tr
void resize (Index size) inline inherited
Resizes to given size.
References PermutationBase< Derived >::indices().
Index rows (void) const inline inherited
Returns
the number of rows
References PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
void setIdentity () inline inherited
Sets *this to be the identity permutation matrix
References PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
void setIdentity (Index size) inline inherited
Sets *this to be the identity permutation matrix of given size.
References PermutationBase< Derived >::resize(), and PermutationBase< Derived >::setIdentity().
Index size () const inline inherited
Returns
the size of a side of the respective square matrix, i.e., the number of indices
References PermutationBase< Derived >::indices(), and PermutationBase< Derived >::size().
DenseMatrixType toDenseMatrix () const inline inherited
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
References EigenBase< Derived >::derived().
Transpose<PermutationBase> transpose () const inline inherited
Returns
the tranpose permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
References EigenBase< Derived >::derived().
The documentation for this class was generated from the following file:
PermutationMatrix.h