SparseMatrixBase< Derived > Class Template Reference
SparseMatrixBase< Derived > Class Template Reference
SparseCore module
Base class of any sparse matrices or sparse expressions.
#include <SparseMatrixBase.h>
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime ,
IsVectorAtCompileTime,
Flags,
CoeffReadCost
}
Public Member Functions
template<typename CustomBinaryOp , typename OtherDerived >
const CwiseBinaryOp
< CustomBinaryOp, const
Derived, const OtherDerived > binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
template<typename NewType >
internal::cast_return_type
< Derived, const CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< Derived >::Scalar, NewType >
, const Derived > >::type cast () const
SparseInnerVectorSet< Derived, 1 > col (Index j)
const SparseInnerVectorSet
< Derived, 1 > col (Index j) const
Index cols () const
ConjugateReturnType conjugate () const
const CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const Derived > cwiseAbs () const
const CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const Derived > cwiseAbs2 () const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const Derived > cwiseEqual (const Scalar &s) const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const Derived > cwiseInverse () const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const OtherDerived > cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const OtherDerived > cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const Derived, const
OtherDerived > cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const Derived,
const OtherDerived > cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const Derived > cwiseSqrt () const
Derived & derived ()
const Derived & derived () const
const internal::eval< Derived >
::type eval () const
const ImagReturnType imag () const
NonConstImagReturnType imag ()
Index innerSize () const
SparseInnerVectorSet< Derived, 1 > innerVector (Index outer)
const SparseInnerVectorSet
< Derived, 1 > innerVector (Index outer) const
SparseInnerVectorSet< Derived,
Dynamic > innerVectors (Index outerStart, Index outerSize)
const SparseInnerVectorSet
< Derived, Dynamic > innerVectors (Index outerStart, Index outerSize) const
bool isVector () const
SparseInnerVectorSet< Derived,
Dynamic > middleCols (Index start, Index size)
const SparseInnerVectorSet
< Derived, Dynamic > middleCols (Index start, Index size) const
SparseInnerVectorSet< Derived,
Dynamic > middleRows (Index start, Index size)
const SparseInnerVectorSet
< Derived, Dynamic > middleRows (Index start, Index size) const
Index nonZeros () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const Derived > operator* (const std::complex< Scalar > &scalar) const
template<typename OtherDerived >
const
SparseSparseProductReturnType
< Derived, OtherDerived >
::Type operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const
SparseDenseProductReturnType
< Derived, OtherDerived >
::Type operator* (const MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator- () const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< Derived >::Scalar >, const
Derived > operator/ (const Scalar &scalar) const
Index outerSize () const
RealReturnType real () const
NonConstRealReturnType real ()
SparseInnerVectorSet< Derived, 1 > row (Index i)
const SparseInnerVectorSet
< Derived, 1 > row (Index i) const
Index rows () const
Index size () const
SparseSymmetricPermutationProduct
< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
template<typename CustomUnaryOp >
const CwiseUnaryOp
< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
template<typename CustomViewOp >
const CwiseUnaryView
< CustomViewOp, const Derived > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
Friends
template<typename OtherDerived >
const
DenseSparseProductReturnType
< OtherDerived, Derived >
::Type operator* (const MatrixBase< OtherDerived > &lhs, const Derived &rhs)
Detailed Description
template<typename Derived>
class Eigen::SparseMatrixBase< Derived >
Base class of any sparse matrices or sparse expressions.
Template Parameters
Derived This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_SPARSEMATRIXBASE_PLUGIN.
Member Enumeration Documentation
anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See Also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See Also
RowsAtCompileTime, ColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Member Function Documentation
const CwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See Also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See Also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template binary functor
template<typename Scalar> struct MakeComplexOp {
  EIGEN_EMPTY_STRUCT_CTOR(MakeComplexOp)
  typedef complex<Scalar> result_type;
  complex<Scalar> operator()(const Scalar& a, const Scalar& b) const { return complex<Scalar>(a,b); }
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random(), m2 = Matrix4d::Random();
  cout << m1.binaryExpr(m2, MakeComplexOp<double>()) << endl;
  return 0;
}
Output:
   (0.68,0.271)  (0.823,-0.967) (-0.444,-0.687)   (-0.27,0.998)
 (-0.211,0.435) (-0.605,-0.514)  (0.108,-0.198) (0.0268,-0.563)
 (0.566,-0.717)  (-0.33,-0.726) (-0.0452,-0.74)  (0.904,0.0259)
  (0.597,0.214)   (0.536,0.608)  (0.258,-0.782)   (0.832,0.678)
See Also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
internal::cast_return_type<Derived,const CwiseUnaryOp<internal::scalar_cast_op<typename internal::traits<Derived>::Scalar, NewType>, const Derived> >::type cast () const inline
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See Also
class CwiseUnaryOp
SparseInnerVectorSet< Derived, 1 > col (Index i)
Returns
the i-th column of the matrix *this. For column-major matrix only.
const SparseInnerVectorSet< Derived, 1 > col (Index i) const
Returns
the i-th column of the matrix *this. For column-major matrix only. (read-only version)
Index cols (void) const inline
Returns
the number of columns.
See Also
rows()
Referenced by SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size().
ConjugateReturnType conjugate () const inline
Returns
an expression of the complex conjugate of *this.
See Also
adjoint()
const CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> cwiseAbs () const inline
Returns
an expression of the coefficient-wise absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs() << endl;
Output:
2 4 6
5 1 0
See Also
cwiseAbs2()
const CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const Derived> cwiseAbs2 () const inline
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs2() << endl;
Output:
 4 16 36
25  1  0
See Also
cwiseAbs()
const CwiseUnaryOp<std::binder1st<std::equal_to<Scalar> >, const Derived> cwiseEqual (const Scalar & s) const inline
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See Also
cwiseEqual(const MatrixBase<OtherDerived> &) const
const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> cwiseInverse () const inline
Returns
an expression of the coefficient-wise inverse of *this.
Example:
MatrixXd m(2,3);
m << 2, 0.5, 1,
     3, 0.25, 1;
cout << m.cwiseInverse() << endl;
Output:
0.5 2 1
0.333 4 1
See Also
cwiseProduct()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const OtherDerived> cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise max of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMax(w) << endl;
Output:
4
3
4
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const ConstantReturnType> cwiseMax (const Scalar & other) const inline
Returns
an expression of the coefficient-wise max of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const OtherDerived> cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise min of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMin(w) << endl;
Output:
2
2
3
See Also
class CwiseBinaryOp, max()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const ConstantReturnType> cwiseMin (const Scalar & other) const inline
Returns
an expression of the coefficient-wise min of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseNotEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseNotEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are not equal: " << count << endl;
Output:
Comparing m with identity matrix:
0 0
1 0
Number of coefficients that are not equal: 1
See Also
cwiseEqual(), isApprox(), isMuchSmallerThan()
const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseQuotient(w) << endl;
Output:
0.5
1.5
1.33
See Also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
const CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> cwiseSqrt () const inline
Returns
an expression of the coefficient-wise square root of *this.
Example:
Vector3d v(1,2,4);
cout << v.cwiseSqrt() << endl;
Output:
1
1.41
2
See Also
cwisePow(), cwiseSquare()
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::imag(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), RotationBase< Derived, 3 >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), SparseMatrixBase< Derived >::operator*(), Transform< Scalar, Dim, Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), DenseBase< Derived >::operator=(), Transform< Scalar, Dim, Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), Transform< Scalar, Dim, Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
const internal::eval<Derived>::type eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
const ImagReturnType imag () const inline
Returns
an read-only expression of the imaginary part of *this.
See Also
real()
NonConstImagReturnType imag () inline
Returns
a non const expression of the imaginary part of *this.
See Also
real()
Index innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
SparseInnerVectorSet< Derived, 1 > innerVector (Index outer)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
const SparseInnerVectorSet< Derived, 1 > innerVector (Index outer) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
SparseInnerVectorSet< Derived, Dynamic > innerVectors (Index outerStart, Index outerSize)
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major).
const SparseInnerVectorSet< Derived, Dynamic > innerVectors (Index outerStart, Index outerSize) const
Returns
the outer -th column (resp. row) of the matrix *this if *this is col-major (resp. row-major). Read-only.
bool isVector () const inline
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
SparseInnerVectorSet< Derived, Dynamic > middleCols (Index start, Index size)
Returns
the i-th column of the matrix *this. For column-major matrix only.
const SparseInnerVectorSet< Derived, Dynamic > middleCols (Index start, Index size) const
Returns
the i-th column of the matrix *this. For column-major matrix only. (read-only version)
SparseInnerVectorSet< Derived, Dynamic > middleRows (Index start, Index size)
Returns
the i-th row of the matrix *this. For row-major matrix only.
const SparseInnerVectorSet< Derived, Dynamic > middleRows (Index start, Index size) const
Returns
the i-th row of the matrix *this. For row-major matrix only. (read-only version)
Index nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
const ScalarMultipleReturnType operator* (const Scalar & scalar) const inline
Returns
an expression of *this scaled by the scalar factor scalar
const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const Derived> operator* (const std::complex< Scalar > & scalar) const inline
Overloaded for efficient real matrix times complex scalar value
const SparseSparseProductReturnType< Derived, OtherDerived >::Type operator* (const SparseMatrixBase< OtherDerived > & other) const inline
Returns
an expression of the product of two sparse matrices. By default a conservative product preserving the symbolic non zeros is performed. The automatic pruning of the small values can be achieved by calling the pruned() function in which case a totally different product algorithm is employed:
C = (A*B).pruned();             // supress numerical zeros (exact)
C = (A*B).pruned(ref);
C = (A*B).pruned(ref,epsilon);
where ref is a meaningful non zero reference value.
References EigenBase< Derived >::derived().
const SparseDenseProductReturnType< Derived, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > & other) const inline
sparse * dense (returns a dense object unless it is an outer product)
const CwiseUnaryOp<internal::scalar_opposite_op<typename internal::traits<Derived>::Scalar>, const Derived> operator- () const inline
Returns
an expression of the opposite of *this
const CwiseUnaryOp<internal::scalar_quotient1_op<typename internal::traits<Derived>::Scalar>, const Derived> operator/ (const Scalar & scalar) const inline
Returns
an expression of *this divided by the scalar value scalar
Index outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
RealReturnType real () const inline
Returns
a read-only expression of the real part of *this.
See Also
imag()
NonConstRealReturnType real () inline
Returns
a non const expression of the real part of *this.
See Also
imag()
SparseInnerVectorSet< Derived, 1 > row (Index i)
Returns
the i-th row of the matrix *this. For row-major matrix only.
const SparseInnerVectorSet< Derived, 1 > row (Index i) const
Returns
the i-th row of the matrix *this. For row-major matrix only. (read-only version)
Index rows (void) const inline
Returns
the number of rows.
See Also
cols()
Referenced by SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::isVector(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::outerSize(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::size(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), and CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve().
Index size () const inline
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols().
SparseSymmetricPermutationProduct<Derived,Upper|Lower> twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > & perm) const inline
Returns
an expression of P H P^-1 where H is the matrix represented by *this
const CwiseUnaryOp<CustomUnaryOp, const Derived> unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define function to be applied coefficient-wise
double ramp(double x)
{
  if (x > 0)
    return x;
  else
    return 0;
}
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(ptr_fun(ramp)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
  0.68  0.823      0      0
     0      0  0.108 0.0268
 0.566      0      0  0.904
 0.597  0.536  0.258  0.832
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
const CwiseUnaryView<CustomViewOp, const Derived> unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
Friends And Related Function Documentation
const DenseSparseProductReturnType<OtherDerived,Derived>::Type operator* (const MatrixBase< OtherDerived > & lhs, const Derived & rhs) friend
dense * sparse (return a dense object unless it is an outer product)
The documentation for this class was generated from the following files:
SparseMatrixBase.h
CommonCwiseUnaryOps.h
CommonCwiseBinaryOps.h
MatrixCwiseUnaryOps.h
MatrixCwiseBinaryOps.h
SparseBlock.h
SparseCwiseBinaryOp.h
SparseCwiseUnaryOp.h
SparseDenseProduct.h
SparseDiagonalProduct.h
SparseDot.h
SparseProduct.h
SparseRedux.h
SparseSelfAdjointView.h
SparseTriangularView.h