SparseVector< _Scalar, _Flags, _Index > Class Template Reference
SparseVector< _Scalar, _Flags, _Index > Class Template Reference
SparseCore module
a sparse vector class
#include <SparseVector.h>
Public Member Functions
const CwiseBinaryOp
< CustomBinaryOp, const
SparseVector< _Scalar,
_Options, _Index >, const
OtherDerived > binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > &other, const CustomBinaryOp &func=CustomBinaryOp()) const
internal::cast_return_type
< SparseVector< _Scalar,
_Options, _Index >, const
CwiseUnaryOp
< internal::scalar_cast_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar,
NewType >, const SparseVector
< _Scalar, _Options, _Index >
> >::type cast () const
Scalar & coeffRef (Index i)
ConjugateReturnType conjugate () const
const CwiseUnaryOp
< internal::scalar_abs_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseAbs () const
const CwiseUnaryOp
< internal::scalar_abs2_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseAbs2 () const
const CwiseUnaryOp
< std::binder1st
< std::equal_to< Scalar >
>, const SparseVector
< _Scalar, _Options, _Index > > cwiseEqual (const Scalar &s) const
const CwiseUnaryOp
< internal::scalar_inverse_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseInverse () const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMax (const Scalar &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const ConstantReturnType > cwiseMin (const Scalar &other) const
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const SparseVector< _Scalar,
_Options, _Index >, const
OtherDerived > cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index >
, const OtherDerived > cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_sqrt_op
< Scalar >, const SparseVector
< _Scalar, _Options, _Index > > cwiseSqrt () const
Derived & derived ()
const Derived & derived () const
EIGEN_DEPRECATED void endFill ()
const internal::eval
< SparseVector< _Scalar,
_Options, _Index > >::type eval () const
EIGEN_DEPRECATED Scalar & fill (Index r, Index c)
EIGEN_DEPRECATED Scalar & fill (Index i)
EIGEN_DEPRECATED Scalar & fillrand (Index r, Index c)
EIGEN_DEPRECATED Scalar & fillrand (Index i)
const ImagReturnType imag () const
NonConstImagReturnType imag ()
bool isVector () const
Index nonZeros () const
const ScalarMultipleReturnType operator* (const Scalar &scalar) const
const CwiseUnaryOp
< internal::scalar_multiple2_op
< Scalar, std::complex< Scalar >
>, const SparseVector
< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > &scalar) const
const
SparseDenseProductReturnType
< SparseVector< _Scalar,
_Options, _Index >
, OtherDerived >::Type operator* (const MatrixBase< OtherDerived > &other) const
const CwiseUnaryOp
< internal::scalar_opposite_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar >
, const SparseVector< _Scalar,
_Options, _Index > > operator- () const
const CwiseUnaryOp
< internal::scalar_quotient1_op
< typename internal::traits
< SparseVector< _Scalar,
_Options, _Index > >::Scalar >
, const SparseVector< _Scalar,
_Options, _Index > > operator/ (const Scalar &scalar) const
RealReturnType real () const
NonConstRealReturnType real ()
Index size () const
EIGEN_DEPRECATED void startFill (Index reserve)
Scalar sum () const
SparseSymmetricPermutationProduct
< SparseVector< _Scalar,
_Options, _Index >, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
const CwiseUnaryOp
< CustomUnaryOp, const
SparseVector< _Scalar,
_Options, _Index > > unaryExpr (const CustomUnaryOp &func=CustomUnaryOp()) const
Apply a unary operator coefficient-wise.
const CwiseUnaryView
< CustomViewOp, const
SparseVector< _Scalar,
_Options, _Index > > unaryViewExpr (const CustomViewOp &func=CustomViewOp()) const
~SparseVector ()
Detailed Description
template<typename _Scalar, int _Flags = 0, typename _Index = int>
class Eigen::SparseVector< _Scalar, _Flags, _Index >
a sparse vector class
Template Parameters
_Scalar the scalar type, i.e. the type of the coefficients
See http://www.netlib.org/linalg/html_templates/node91.html for details on the storage scheme.
This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_SPARSEVECTOR_PLUGIN.
Constructor & Destructor Documentation
~SparseVector () inline
Destructor
Member Function Documentation
const CwiseBinaryOp<CustomBinaryOp, const SparseVector< _Scalar, _Options, _Index > , const OtherDerived> binaryExpr (const Eigen::SparseMatrixBase< OtherDerived > & other, const CustomBinaryOp & func = CustomBinaryOp()) const inline inherited
Returns
an expression of the difference of *this and other
Note
If you want to substract a given scalar from all coefficients, see Cwise::operator-().
See Also
class CwiseBinaryOp, operator-=()
Returns
an expression of the sum of *this and other
Note
If you want to add a given scalar to all coefficients, see Cwise::operator+().
See Also
class CwiseBinaryOp, operator+=()
Returns
an expression of a custom coefficient-wise operator func of *this and other
The template parameter CustomBinaryOp is the type of the functor of the custom operator (see class CwiseBinaryOp for an example)
Here is an example illustrating the use of custom functors:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template binary functor
template<typename Scalar> struct MakeComplexOp {
  EIGEN_EMPTY_STRUCT_CTOR(MakeComplexOp)
  typedef complex<Scalar> result_type;
  complex<Scalar> operator()(const Scalar& a, const Scalar& b) const { return complex<Scalar>(a,b); }
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random(), m2 = Matrix4d::Random();
  cout << m1.binaryExpr(m2, MakeComplexOp<double>()) << endl;
  return 0;
}
Output:
   (0.68,0.271)  (0.823,-0.967) (-0.444,-0.687)   (-0.27,0.998)
 (-0.211,0.435) (-0.605,-0.514)  (0.108,-0.198) (0.0268,-0.563)
 (0.566,-0.717)  (-0.33,-0.726) (-0.0452,-0.74)  (0.904,0.0259)
  (0.597,0.214)   (0.536,0.608)  (0.258,-0.782)   (0.832,0.678)
See Also
class CwiseBinaryOp, operator+(), operator-(), cwiseProduct()
internal::cast_return_type<SparseVector< _Scalar, _Options, _Index > ,const CwiseUnaryOp<internal::scalar_cast_op<typename internal::traits<SparseVector< _Scalar, _Options, _Index > >::Scalar, NewType>, const SparseVector< _Scalar, _Options, _Index > > >::type cast () const inline inherited
Returns
an expression of *this with the Scalar type casted to NewScalar.
The template parameter NewScalar is the type we are casting the scalars to.
See Also
class CwiseUnaryOp
Scalar& coeffRef (Index i) inline
Returns
a reference to the coefficient value at given index i This operation involes a log(rho*size) binary search. If the coefficient does not exist yet, then a sorted insertion into a sequential buffer is performed.
This insertion might be very costly if the number of nonzeros above i is large.
ConjugateReturnType conjugate () const inline inherited
Returns
an expression of the complex conjugate of *this.
See Also
adjoint()
const CwiseUnaryOp<internal::scalar_abs_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > > cwiseAbs () const inline inherited
Returns
an expression of the coefficient-wise absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs() << endl;
Output:
2 4 6
5 1 0
See Also
cwiseAbs2()
const CwiseUnaryOp<internal::scalar_abs2_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > > cwiseAbs2 () const inline inherited
Returns
an expression of the coefficient-wise squared absolute value of *this
Example:
MatrixXd m(2,3);
m << 2, -4, 6,
     -5, 1, 0;
cout << m.cwiseAbs2() << endl;
Output:
 4 16 36
25  1  0
See Also
cwiseAbs()
const CwiseUnaryOp<std::binder1st<std::equal_to<Scalar> >, const SparseVector< _Scalar, _Options, _Index > > cwiseEqual (const Scalar & s) const inline inherited
Returns
an expression of the coefficient-wise == operator of *this and a scalar s
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
See Also
cwiseEqual(const MatrixBase<OtherDerived> &) const
const CwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > > cwiseInverse () const inline inherited
Returns
an expression of the coefficient-wise inverse of *this.
Example:
MatrixXd m(2,3);
m << 2, 0.5, 1,
     3, 0.25, 1;
cout << m.cwiseInverse() << endl;
Output:
0.5 2 1
0.333 4 1
See Also
cwiseProduct()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const OtherDerived> cwiseMax (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise max of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMax(w) << endl;
Output:
4
3
4
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const ConstantReturnType> cwiseMax (const Scalar & other) const inline inherited
Returns
an expression of the coefficient-wise max of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const OtherDerived> cwiseMin (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise min of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMin(w) << endl;
Output:
2
2
3
See Also
class CwiseBinaryOp, max()
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const ConstantReturnType> cwiseMin (const Scalar & other) const inline inherited
Returns
an expression of the coefficient-wise min of *this and scalar other
See Also
class CwiseBinaryOp, min()
const CwiseBinaryOp<std::not_equal_to<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const OtherDerived> cwiseNotEqual (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise != operator of *this and other
Warning
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseNotEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseNotEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are not equal: " << count << endl;
Output:
Comparing m with identity matrix:
0 0
1 0
Number of coefficients that are not equal: 1
See Also
cwiseEqual(), isApprox(), isMuchSmallerThan()
const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > , const OtherDerived> cwiseQuotient (const Eigen::SparseMatrixBase< OtherDerived > & other) const inline inherited
Returns
an expression of the coefficient-wise quotient of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseQuotient(w) << endl;
Output:
0.5
1.5
1.33
See Also
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
const CwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const SparseVector< _Scalar, _Options, _Index > > cwiseSqrt () const inline inherited
Returns
an expression of the coefficient-wise square root of *this.
Example:
Vector3d v(1,2,4);
cout << v.cwiseSqrt() << endl;
Output:
1
1.41
2
See Also
cwisePow(), cwiseSquare()
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by MatrixBase< Derived >::applyOnTheLeft(), MatrixBase< Derived >::applyOnTheRight(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheLeft(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::applyTranspositionOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::binaryExpr(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::imag(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::indices(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::inverse(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), RotationBase< Derived, 3 >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), SparseMatrixBase< Derived >::operator*(), Transform< Scalar, Dim, Mode, _Options >::operator*(), Eigen::operator*(), MatrixBase< Derived >::operator*=(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator=(), DenseBase< Derived >::operator=(), Transform< Scalar, Dim, Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::toDenseMatrix(), Transform< Scalar, Dim, Mode, _Options >::Transform(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::transpose(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
EIGEN_DEPRECATED void endFill () inline
const internal::eval<SparseVector< _Scalar, _Options, _Index > >::type eval () const inline inherited
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
EIGEN_DEPRECATED Scalar& fill (Index r, Index c) inline
EIGEN_DEPRECATED Scalar& fill (Index i) inline
EIGEN_DEPRECATED Scalar& fillrand (Index r, Index c) inline
EIGEN_DEPRECATED Scalar& fillrand (Index i) inline
const ImagReturnType imag () const inline inherited
Returns
an read-only expression of the imaginary part of *this.
See Also
real()
NonConstImagReturnType imag () inline inherited
Returns
a non const expression of the imaginary part of *this.
See Also
real()
bool isVector () const inline inherited
Returns
true if either the number of rows or the number of columns is equal to 1. In other words, this function returns
rows()==1 || cols()==1
See Also
rows(), cols(), IsVectorAtCompileTime.
Index nonZeros () const inline
Returns
the number of non zero coefficients
const ScalarMultipleReturnType operator* (const Scalar & scalar) const inline inherited
Returns
an expression of *this scaled by the scalar factor scalar
const CwiseUnaryOp<internal::scalar_multiple2_op<Scalar,std::complex<Scalar> >, const SparseVector< _Scalar, _Options, _Index > > operator* (const std::complex< Scalar > & scalar) const inline inherited
Overloaded for efficient real matrix times complex scalar value
const SparseDenseProductReturnType<SparseVector< _Scalar, _Options, _Index > ,OtherDerived>::Type operator* (const MatrixBase< OtherDerived > & other) const inherited
sparse * dense (returns a dense object unless it is an outer product)
const CwiseUnaryOp<internal::scalar_opposite_op<typename internal::traits<SparseVector< _Scalar, _Options, _Index > >::Scalar>, const SparseVector< _Scalar, _Options, _Index > > operator- () const inline inherited
Returns
an expression of the opposite of *this
const CwiseUnaryOp<internal::scalar_quotient1_op<typename internal::traits<SparseVector< _Scalar, _Options, _Index > >::Scalar>, const SparseVector< _Scalar, _Options, _Index > > operator/ (const Scalar & scalar) const inline inherited
Returns
an expression of *this divided by the scalar value scalar
RealReturnType real () const inline inherited
Returns
a read-only expression of the real part of *this.
See Also
imag()
NonConstRealReturnType real () inline inherited
Returns
a non const expression of the real part of *this.
See Also
imag()
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See Also
rows(), cols().
EIGEN_DEPRECATED void startFill (Index reserve) inline
internal::traits< SparseVector< _Scalar, _Options, _Index > >::Scalar sum () const
Overloaded for performance
SparseSymmetricPermutationProduct<SparseVector< _Scalar, _Options, _Index > ,Upper|Lower> twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > & perm) const inline inherited
Returns
an expression of P H P^-1 where H is the matrix represented by *this
const CwiseUnaryOp<CustomUnaryOp, const SparseVector< _Scalar, _Options, _Index > > unaryExpr (const CustomUnaryOp & func = CustomUnaryOp()) const inline inherited
Apply a unary operator coefficient-wise.
Parameters
[in] func Functor implementing the unary operator
Template Parameters
CustomUnaryOp Type of func
Returns
An expression of a custom coefficient-wise unary operator func of *this
The function ptr_fun() from the C++ standard library can be used to make functors out of normal functions.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define function to be applied coefficient-wise
double ramp(double x)
{
  if (x > 0)
    return x;
  else
    return 0;
}
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(ptr_fun(ramp)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
  0.68  0.823      0      0
     0      0  0.108 0.0268
 0.566      0      0  0.904
 0.597  0.536  0.258  0.832
Genuine functors allow for more possibilities, for instance it may contain a state.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
const CwiseUnaryView<CustomViewOp, const SparseVector< _Scalar, _Options, _Index > > unaryViewExpr (const CustomViewOp & func = CustomViewOp()) const inline inherited
Returns
an expression of a custom coefficient-wise unary operator func of *this
The template parameter CustomUnaryOp is the type of the functor of the custom unary operator.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
// define a custom template unary functor
template<typename Scalar>
struct CwiseClampOp {
  CwiseClampOp(const Scalar& inf, const Scalar& sup) : m_inf(inf), m_sup(sup) {}
  const Scalar operator()(const Scalar& x) const { return x<m_inf ? m_inf : (x>m_sup ? m_sup : x); }
  Scalar m_inf, m_sup;
};
int main(int, char**)
{
  Matrix4d m1 = Matrix4d::Random();
  cout << m1 << endl << "becomes: " << endl << m1.unaryExpr(CwiseClampOp<double>(-0.5,0.5)) << endl;
  return 0;
}
Output:
   0.68   0.823  -0.444   -0.27
 -0.211  -0.605   0.108  0.0268
  0.566   -0.33 -0.0452   0.904
  0.597   0.536   0.258   0.832
becomes:
    0.5     0.5  -0.444   -0.27
 -0.211    -0.5   0.108  0.0268
    0.5   -0.33 -0.0452     0.5
    0.5     0.5   0.258     0.5
See Also
class CwiseUnaryOp, class CwiseBinaryOp
The documentation for this class was generated from the following files:
SparseUtil.h
SparseVector.h
SparseRedux.h