QuaternionBase< Derived > Class Template Reference
QuaternionBase< Derived > Class Template Reference
Geometry module
Base class for quaternion expressions.
#include <Quaternion.h>
Public Types
typedef AngleAxis< Scalar > AngleAxisType
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, 3, 1 > Vector3
Public Member Functions
Vector3 _transformVector (Vector3 v) const
template<class OtherDerived >
internal::traits< Derived >::Scalar angularDistance (const QuaternionBase< OtherDerived > &other) const
template<typename NewScalarType >
internal::cast_return_type
< Derived, Quaternion
< NewScalarType > >::type cast () const
const internal::traits
< Derived >::Coefficients & coeffs () const
internal::traits< Derived >
::Coefficients & coeffs ()
Quaternion< Scalar > conjugate () const
template<class OtherDerived >
Scalar dot (const QuaternionBase< OtherDerived > &other) const
Quaternion< Scalar > inverse () const
template<class OtherDerived >
bool isApprox (const QuaternionBase< OtherDerived > &other, RealScalar prec=NumTraits< Scalar >::dummy_precision()) const
RotationMatrixType matrix () const
Scalar norm () const
void normalize ()
Quaternion< Scalar > normalized () const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
internal::rotation_base_generic_product_selector
< Derived, OtherDerived,
OtherDerived::IsVectorAtCompileTime >
::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<class OtherDerived >
Quaternion< typename
internal::traits< Derived >
::Scalar > operator* (const QuaternionBase< OtherDerived > &other) const
template<class OtherDerived >
Derived & operator*= (const QuaternionBase< OtherDerived > &q)
Derived & operator= (const AngleAxisType &aa)
template<class MatrixDerived >
Derived & operator= (const MatrixBase< MatrixDerived > &xpr)
template<typename Derived1 , typename Derived2 >
Derived & setFromTwoVectors (const MatrixBase< Derived1 > &a, const MatrixBase< Derived2 > &b)
QuaternionBase & setIdentity ()
template<class OtherDerived >
Quaternion< Scalar > slerp (Scalar t, const QuaternionBase< OtherDerived > &other) const
template<class OtherDerived >
Quaternion< typename
internal::traits< Derived >
::Scalar > slerp (Scalar t, const QuaternionBase< OtherDerived > &other) const
Scalar squaredNorm () const
Matrix3 toRotationMatrix () const
const VectorBlock< const
Coefficients, 3 > vec () const
VectorBlock< Coefficients, 3 > vec ()
Scalar w () const
Scalar & w ()
Scalar x () const
Scalar & x ()
Scalar y () const
Scalar & y ()
Scalar z () const
Scalar & z ()
Static Public Member Functions
static Quaternion< Scalar > Identity ()
Detailed Description
template<typename Derived>
class Eigen::QuaternionBase< Derived >
Base class for quaternion expressions.
This is defined in the Geometry module.
#include <Eigen/Geometry>
Template Parameters
Derived derived type (CRTP)
See Also
class Quaternion
Member Typedef Documentation
typedef AngleAxis<Scalar> AngleAxisType
the equivalent angle-axis type
typedef Matrix<Scalar,3,3> Matrix3
the equivalent rotation matrix type
typedef Matrix<Scalar,Dim,Dim> RotationMatrixType inherited
corresponding linear transformation matrix type
typedef Matrix<Scalar,3,1> Vector3
the type of a 3D vector
Member Function Documentation
QuaternionBase< Derived >::Vector3 _transformVector (Vector3 v) const inline
return the result vector of v through the rotation
Rotation of a vector by a quaternion.
Remarks
If the quaternion is used to rotate several points (>1) then it is much more efficient to first convert it to a 3x3 Matrix. Comparison of the operation cost for n transformations:
Quaternion2: 30n
Via a Matrix3: 24 + 15n
internal::traits<Derived>::Scalar angularDistance (const QuaternionBase< OtherDerived > & other) const inline
Returns
the angle (in radian) between two rotations
See Also
dot()
internal::cast_return_type<Derived,Quaternion<NewScalarType> >::type cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
const internal::traits<Derived>::Coefficients& coeffs () const inline
Returns
a read-only vector expression of the coefficients (x,y,z,w)
Referenced by QuaternionBase< Quaternion< _Scalar, _Options > >::dot(), QuaternionBase< Quaternion< _Scalar, _Options > >::isApprox(), QuaternionBase< Quaternion< _Scalar, _Options > >::norm(), QuaternionBase< Quaternion< _Scalar, _Options > >::normalize(), QuaternionBase< Quaternion< _Scalar, _Options > >::normalized(), QuaternionBase< Quaternion< _Scalar, _Options > >::setIdentity(), QuaternionBase< Quaternion< _Scalar, _Options > >::squaredNorm(), and QuaternionBase< Quaternion< _Scalar, _Options > >::vec().
internal::traits<Derived>::Coefficients& coeffs () inline
Returns
a vector expression of the coefficients (x,y,z,w)
Quaternion< typename internal::traits< Derived >::Scalar > conjugate () const inline
Returns
the conjugated quaternion
the conjugate of the *this which is equal to the multiplicative inverse if the quaternion is normalized. The conjugate of a quaternion represents the opposite rotation.
See Also
Quaternion2::inverse()
Scalar dot (const QuaternionBase< OtherDerived > & other) const inline
Returns
the dot product of *this and other Geometrically speaking, the dot product of two unit quaternions corresponds to the cosine of half the angle between the two rotations.
See Also
angularDistance()
static Quaternion<Scalar> Identity () inline static
Returns
a quaternion representing an identity rotation
See Also
MatrixBase::Identity()
Quaternion< typename internal::traits< Derived >::Scalar > inverse () const inline
Returns
the quaternion describing the inverse rotation
the multiplicative inverse of *this Note that in most cases, i.e., if you simply want the opposite rotation, and/or the quaternion is normalized, then it is enough to use the conjugate.
See Also
QuaternionBase::conjugate()
bool isApprox (const QuaternionBase< OtherDerived > & other, RealScalar prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See Also
MatrixBase::isApprox()
RotationMatrixType matrix () const inline inherited
Returns
an equivalent rotation matrix This function is added to be conform with the Transform class' naming scheme.
Scalar norm () const inline
Returns
the norm of the quaternion's coefficients
See Also
QuaternionBase::squaredNorm(), MatrixBase::norm()
void normalize (void) inline
Normalizes the quaternion *this
See Also
normalized(), MatrixBase::normalize()
Quaternion<Scalar> normalized () const inline
Returns
a normalized copy of *this
See Also
normalize(), MatrixBase::normalized()
Transform<Scalar,Dim,Isometry> operator* (const Translation< Scalar, Dim > & t) const inline inherited
Returns
the concatenation of the rotation *this with a translation t
RotationMatrixType operator* (const UniformScaling< Scalar > & s) const inline inherited
Returns
the concatenation of the rotation *this with a uniform scaling s
References RotationBase< Derived, _Dim >::toRotationMatrix().
internal::rotation_base_generic_product_selector<Derived,OtherDerived,OtherDerived::IsVectorAtCompileTime>::ReturnType operator* (const EigenBase< OtherDerived > & e) const inline inherited
Returns
the concatenation of the rotation *this with a generic expression e e can be:
a DimxDim linear transformation matrix
a DimxDim diagonal matrix (axis aligned scaling)
a vector of size Dim
References EigenBase< Derived >::derived().
Transform<Scalar,Dim,Mode> operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline inherited
Returns
the concatenation of the rotation *this with a transformation t
References RotationBase< Derived, _Dim >::toRotationMatrix().
Quaternion<typename internal::traits<Derived>::Scalar> operator* (const QuaternionBase< OtherDerived > & other) const inline
Returns
the concatenation of two rotations as a quaternion-quaternion product
Derived & operator*= (const QuaternionBase< OtherDerived > & other) inline
See Also
operator*(Quaternion)
Derived & operator= (const AngleAxisType & aa) inline
Set *this from an angle-axis aa and returns a reference to *this
Derived& operator= (const MatrixBase< MatrixDerived > & xpr) inline
Set *this from the expression xpr:
if xpr is a 4x1 vector, then xpr is assumed to be a quaternion
if xpr is a 3x3 matrix, then xpr is assumed to be rotation matrix and xpr is converted to a quaternion
Derived & setFromTwoVectors (const MatrixBase< Derived1 > & a, const MatrixBase< Derived2 > & b) inline
Returns
the quaternion which transform a into b through a rotation
Sets *this to be a quaternion representing a rotation between the two arbitrary vectors a and b. In other words, the built rotation represent a rotation sending the line of direction a to the line of direction b, both lines passing through the origin.
Returns
a reference to *this.
Note that the two input vectors do not have to be normalized, and do not need to have the same norm.
References Eigen::ComputeFullV, JacobiSVD< MatrixType, QRPreconditioner >::matrixV(), and MatrixBase< Derived >::normalized().
QuaternionBase& setIdentity () inline
See Also
QuaternionBase::Identity(), MatrixBase::setIdentity()
Quaternion<Scalar> slerp (Scalar t, const QuaternionBase< OtherDerived > & other) const
Returns
an interpolation for a constant motion between other and *this t in [0;1] see http://en.wikipedia.org/wiki/Slerp
Quaternion<typename internal::traits<Derived>::Scalar> slerp (Scalar t, const QuaternionBase< OtherDerived > & other) const
Returns
the spherical linear interpolation between the two quaternions *this and other at the parameter t
Scalar squaredNorm () const inline
Returns
the squared norm of the quaternion's coefficients
See Also
QuaternionBase::norm(), MatrixBase::squaredNorm()
QuaternionBase< Derived >::Matrix3 toRotationMatrix (void) const inline
Returns
an equivalent 3x3 rotation matrix
Convert the quaternion to a 3x3 rotation matrix. The quaternion is required to be normalized, otherwise the result is undefined.
const VectorBlock<const Coefficients,3> vec () const inline
Returns
a read-only vector expression of the imaginary part (x,y,z)
Referenced by AngleAxis< Scalar >::operator=().
VectorBlock<Coefficients,3> vec () inline
Returns
a vector expression of the imaginary part (x,y,z)
Scalar w () const inline
Returns
the w coefficient
Referenced by AngleAxis< Scalar >::operator=().
Scalar& w () inline
Returns
a reference to the w coefficient
Scalar x () const inline
Returns
the x coefficient
Scalar& x () inline
Returns
a reference to the x coefficient
Scalar y () const inline
Returns
the y coefficient
Scalar& y () inline
Returns
a reference to the y coefficient
Scalar z () const inline
Returns
the z coefficient
Scalar& z () inline
Returns
a reference to the z coefficient
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Quaternion.h