ReturnByValue< Derived > Class Template Reference
ReturnByValue< Derived > Class Template Reference
Core module
#include <ReturnByValue.h>
Inherits type< ReturnByValue< Derived > >.
Public Types
typedef
internal::dense_xpr_base
< ReturnByValue >::type Base
typedef internal::traits
< Derived >::ReturnType ReturnType
Public Member Functions
Index cols () const
template<typename Dest >
void evalTo (Dest &dst) const
Index rows () const
template<typename Derived>
class Eigen::ReturnByValue< Derived >
Member Typedef Documentation
typedef internal::dense_xpr_base<ReturnByValue>::type Base
typedef internal::traits<Derived>::ReturnType ReturnType
Member Function Documentation
Index cols (void) const [inline]
Referenced by Array< Index, 64, 1 >::Array(), ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::cols(), Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), and PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=().
void evalTo (Dest & dst) const [inline]
Referenced by Array< Index, 64, 1 >::Array(), ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::evalTo(), Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), MatrixBase< Derived >::operator=(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), and Transform< _Scalar, _Dim, _Mode, _Options >::Transform().
Index rows (void) const [inline]
Referenced by Array< Index, 64, 1 >::Array(), Matrix< Index, 1, ColsAtCompileTime, RowMajor, 1, MaxColsAtCompileTime >::Matrix(), PlainObjectBase< Matrix< int, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), and ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType > >::rows().
The documentation for this class was generated from the following file:
ReturnByValue.h