MatrixCwiseBinaryOps.h File Reference
MatrixCwiseBinaryOps.h File Reference
Functions
template<typename OtherDerived >
const CwiseBinaryOp
< std::equal_to< Scalar >
, const Derived, const
OtherDerived > cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const OtherDerived > cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_max_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMax (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const OtherDerived > cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
const CwiseBinaryOp
< internal::scalar_min_op
< Scalar >, const Derived,
const ConstantReturnType > cwiseMin (const Scalar &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< std::not_equal_to< Scalar >
, const Derived, const
OtherDerived > cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
const CwiseBinaryOp
< internal::scalar_quotient_op
< Scalar >, const Derived,
const OtherDerived > cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
template<typename OtherDerived >
const EIGEN_CWISE_PRODUCT_RETURN_TYPE (Derived, OtherDerived) cwiseProduct(const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > &other) const
Function Documentation
const CwiseBinaryOp<std::equal_to<Scalar>, const Derived, const OtherDerived> cwiseEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const [inline]
Returns:
an expression of the coefficient-wise == operator of *this and other
Warning:
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are equal: " << count << endl;
Output:
Comparing m with identity matrix:
1 1
0 1
Number of coefficients that are equal: 3
See also:
cwiseNotEqual(), isApprox(), isMuchSmallerThan()
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const OtherDerived> cwiseMax (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const [inline]
Returns:
an expression of the coefficient-wise max of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMax(w) << endl;
Output:
4
3
4
See also:
class CwiseBinaryOp, min()
Referenced by cwiseMax().
const CwiseBinaryOp<internal::scalar_max_op<Scalar>, const Derived, const ConstantReturnType> cwiseMax (const Scalar & other) const [inline]
Returns:
an expression of the coefficient-wise max of *this and scalar other
See also:
class CwiseBinaryOp, min()
References cwiseMax().
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const OtherDerived> cwiseMin (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const [inline]
Returns:
an expression of the coefficient-wise min of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseMin(w) << endl;
Output:
2
2
3
See also:
class CwiseBinaryOp, max()
Referenced by cwiseMin().
const CwiseBinaryOp<internal::scalar_min_op<Scalar>, const Derived, const ConstantReturnType> cwiseMin (const Scalar & other) const [inline]
Returns:
an expression of the coefficient-wise min of *this and scalar other
See also:
class CwiseBinaryOp, min()
References cwiseMin().
const CwiseBinaryOp<std::not_equal_to<Scalar>, const Derived, const OtherDerived> cwiseNotEqual (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const [inline]
Returns:
an expression of the coefficient-wise != operator of *this and other
Warning:
this performs an exact comparison, which is generally a bad idea with floating-point types. In order to check for equality between two vectors or matrices with floating-point coefficients, it is generally a far better idea to use a fuzzy comparison as provided by isApprox() and isMuchSmallerThan().
Example:
MatrixXi m(2,2);
m << 1, 0,
     1, 1;
cout << "Comparing m with identity matrix:" << endl;
cout << m.cwiseNotEqual(MatrixXi::Identity(2,2)) << endl;
int count = m.cwiseNotEqual(MatrixXi::Identity(2,2)).count();
cout << "Number of coefficients that are not equal: " << count << endl;
Output:
Comparing m with identity matrix:
0 0
1 0
Number of coefficients that are not equal: 1
See also:
cwiseEqual(), isApprox(), isMuchSmallerThan()
const CwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> cwiseQuotient (const EIGEN_CURRENT_STORAGE_BASE_CLASS< OtherDerived > & other) const [inline]
Returns:
an expression of the coefficient-wise quotient of *this and other
Example:
Vector3d v(2,3,4), w(4,2,3);
cout << v.cwiseQuotient(w) << endl;
Output:
0.5
1.5
1.33
See also:
class CwiseBinaryOp, cwiseProduct(), cwiseInverse()
const EIGEN_CWISE_PRODUCT_RETURN_TYPE (Derived , OtherDerived) const [inline]
Returns:
an expression of the Schur product (coefficient wise product) of *this and other
Example:
Matrix3i a = Matrix3i::Random(), b = Matrix3i::Random();
Matrix3i c = a.cwiseProduct(b);
cout << "a:\n" << a << "\nb:\n" << b << "\nc:\n" << c << endl;
Output:
a:
 7  6 -3
-2  9  6
 6 -6 -5
b:
 1 -3  9
 0  0  3
 3  9  5
c:
  7 -18 -27
  0   0  18
 18 -54 -25
See also:
class CwiseBinaryOp, cwiseAbs2
References EIGEN_CWISE_PRODUCT_RETURN_TYPE.