QtAlignedMalloc File Reference
QtAlignedMalloc File Reference
#include "Core"
#include "src/Core/util/DisableStupidWarnings.h"
#include "src/Core/util/ReenableStupidWarnings.h"
Defines
#define EIGEN_QTMALLOC_MODULE_H
Functions
void qFree (void *ptr)
void * qMalloc (size_t size)
void * qRealloc (void *ptr, size_t size)
Define Documentation
#define EIGEN_QTMALLOC_MODULE_H
Function Documentation
void qFree (void * ptr)
References Eigen::internal::aligned_free().
void* qMalloc (size_t size)
References Eigen::internal::aligned_malloc().
void* qRealloc (void * ptr, size_t size)
References Eigen::internal::aligned_free(), and Eigen::internal::aligned_malloc().