SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > > Struct Template Reference
#include <SuperLUSupport.h>
Public Types
typedef Matrix< Scalar, Rows,
Cols, Options, MRows, MCols > MatrixType
Static Public Member Functions
static void run (MatrixType &mat, SluMatrix &res)
template<typename Scalar, int Rows, int Cols, int Options, int MRows, int MCols>
struct Eigen::SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >
Member Typedef Documentation
typedef Matrix<Scalar,Rows,Cols,Options,MRows,MCols> MatrixType
Member Function Documentation
static void run (MatrixType & mat, SluMatrix & res) [inline, static]
References PlainObjectBase< Derived >::cols(), PlainObjectBase< Derived >::data(), eigen_assert, SluMatrix::lda, Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols >::outerStride(), Eigen::RowMajor, PlainObjectBase< Derived >::rows(), SluMatrix::setScalarType(), SluMatrix::setStorageType(), SluMatrix::storage, and SluMatrix::values.
The documentation for this struct was generated from the following file:
SuperLUSupport.h