SluMatrix Struct Reference
SluMatrix Struct Reference
#include <SuperLUSupport.h>
Public Member Functions
SluMatrix & operator= (const SluMatrix &other)
template<typename Scalar >
void setScalarType ()
void setStorageType (Stype_t t)
SluMatrix ()
SluMatrix (const SluMatrix &other)
Static Public Member Functions
template<typename MatrixType >
static SluMatrix Map (MatrixBase< MatrixType > &_mat)
template<typename MatrixType >
static SluMatrix Map (SparseMatrixBase< MatrixType > &mat)
Public Attributes
struct {
union {
int lda
int nnz
}
int * innerInd
int * outerInd
void * values
} storage
Constructor & Destructor Documentation
SluMatrix () [inline]
References SluMatrix::storage.
SluMatrix (const SluMatrix & other) [inline]
References SluMatrix::storage.
Member Function Documentation
static SluMatrix Map (MatrixBase< MatrixType > & _mat) [inline, static]
References eigen_assert, SluMatrix::lda, Eigen::RowMajorBit, SluMatrix::setScalarType(), SluMatrix::setStorageType(), SluMatrix::storage, and SluMatrix::values.
Referenced by Eigen::internal::asSluMatrix().
static SluMatrix Map (SparseMatrixBase< MatrixType > & mat) [inline, static]
References SparseMatrixBase< Derived >::cols(), EigenBase< Derived >::derived(), eigen_assert, SluMatrix::innerInd, Eigen::Lower, SluMatrix::nnz, SparseMatrixBase< Derived >::nonZeros(), SluMatrix::outerInd, Eigen::RowMajorBit, SparseMatrixBase< Derived >::rows(), Eigen::SelfAdjoint, SluMatrix::setScalarType(), SluMatrix::setStorageType(), SluMatrix::storage, Eigen::Upper, and SluMatrix::values.
SluMatrix& operator= (const SluMatrix & other) [inline]
References SluMatrix::storage.
void setScalarType () [inline]
References eigen_assert.
Referenced by SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::initFactorization(), SluMatrix::Map(), SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
void setStorageType (Stype_t t) [inline]
References eigen_assert, and SluMatrix::storage.
Referenced by SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::initFactorization(), SluMatrix::Map(), SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
Member Data Documentation
int* innerInd
Referenced by SluMatrix::Map(), Eigen::internal::map_superlu(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
int lda
Referenced by SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::initFactorization(), SluMatrix::Map(), and SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run().
int nnz
Referenced by SluMatrix::Map(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
int* outerInd
Referenced by SluMatrix::Map(), Eigen::internal::map_superlu(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
struct { ... } storage
Referenced by SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::initFactorization(), SluMatrix::Map(), Eigen::internal::map_superlu(), SluMatrix::operator=(), SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), SluMatrixMapHelper< SparseMatrixBase< Derived > >::run(), SluMatrix::setStorageType(), and SluMatrix::SluMatrix().
void* values
Referenced by SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::initFactorization(), SluMatrix::Map(), Eigen::internal::map_superlu(), SluMatrixMapHelper< Matrix< Scalar, Rows, Cols, Options, MRows, MCols > >::run(), and SluMatrixMapHelper< SparseMatrixBase< Derived > >::run().
The documentation for this struct was generated from the following file:
SuperLUSupport.h