# $Id: Makefile,v 1.15 2004/09/03 16:56:35 bob Exp $

include ../c_flags

###########################################################################
#
#        Options
#
#   Examples of depending on libaries: name, then locate path
#        LDLIBS =  -lthing -lregression 
#        LDFLAGS = -Llib
# 
###########################################################################

PROJECT_NAME = random

USES     = utils

OPT = -Ofast -mfpmath=sse -msse3 -m64 -march=native

# OPT = -O0

###########################################################################
#
#	Objects ... objects are listed in order of precedence
#
###########################################################################

level_0   = random.o
level_1   = 		
level_2	  = 	

############################################################################
#
#            INCLUDING RULES AND DEFINITIONS
#
###########################################################################

include ../rules_for_makefiles


